---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: honeypot

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - cilium-network-policy.yaml
  - ingressroute-tcp.yaml

# ConfigMap kept for future customization but not mounted yet
# - configmap.yaml
