---
apiVersion: v1
kind: Service
metadata:
  name: cowrie
  namespace: honeypot
  labels:
    app: cowrie
    app.kubernetes.io/name: cowrie
    app.kubernetes.io/component: honeypot
spec:
  type: ClusterIP
  selector:
    app: cowrie
  ports:
    - name: ssh
      port: 2222
      targetPort: 2222
      protocol: TCP
    - name: telnet
      port: 2223
      targetPort: 2223
      protocol: TCP
