docker_build(
    "congress-data",
    context=".",
    dockerfile="Dockerfile",
    live_update=[
        sync("src/", "/app/src/"),
    ],
)

k8s_yaml(kustomize("k8s/"))
k8s_resource("congress-data", port_forwards=["4000:4000"])
