---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zipline-postgres
  labels:
    app: zipline
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zipline-uploads
  labels:
    app: zipline
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
