---
apiVersion: v1
kind: Service
metadata:
  name: komga
  labels:
    app: komga
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 25600
      targetPort: http
      protocol: TCP
  selector:
    app: komga
