---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iocaine

resources:
  - namespace.yaml
  - configmap.yaml
  - corpus-configmap.yaml
  - deployment.yaml
  - service.yaml
  - cilium-network-policy.yaml
  - ingressroute.yaml
