# VPN Gateway Tiltfile
# Aggregates all vpn-gateway module Tiltfiles

load('ext://k8s_attach', 'k8s_attach')

LABEL_VPN = '6-vpn-gateway'

# Observe Flux-managed VPN workloads
k8s_attach('gluetun', 'deployment/gluetun', namespace='vpn-gateway', labels=[LABEL_VPN])
k8s_attach('secure-chrome', 'deployment/secure-chrome', namespace='vpn-gateway', labels=[LABEL_VPN])
k8s_attach('securexng', 'deployment/securexng', namespace='vpn-gateway', labels=[LABEL_VPN])

# Include rotation module
include('./rotation/Tiltfile')
