apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

resources:
  - namespace.yaml
  - priorityclass.yaml
  - externalsecret.yaml
  - helmrelease.yaml
  - ingressroute.yaml
