---
apiVersion: v1
kind: Service
metadata:
  name: media-ingest
  namespace: media-ingest
  labels:
    app: media-ingest
    app.kubernetes.io/name: media-ingest
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 4000
      targetPort: grpc
      protocol: TCP
  selector:
    app: media-ingest
