---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbgate-data
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fatboy-nfs-appdata
  resources:
    requests:
      storage: 500Mi
