---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload
  labels:
    app: immich
    app.kubernetes.io/name: immich
    app.kubernetes.io/part-of: vpn-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
