---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tubesync
  labels:
    app: tubesync
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`tubesync.talos00`)
      kind: Rule
      services:
        - name: tubesync
          port: 4848
