---
apiVersion: v1
kind: Service
metadata:
  name: tubesync
  labels:
    app: tubesync
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4848
      targetPort: http
      protocol: TCP
  selector:
    app: tubesync
