---
apiVersion: v1
kind: Service
metadata:
  name: dagster-webserver
  labels:
    app: dagster
    app.kubernetes.io/name: dagster
    app.kubernetes.io/component: webserver
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app: dagster
    app.kubernetes.io/component: webserver
