apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crowdsec
resources:
  - externalsecret.yaml
  - cronjob.yaml
configMapGenerator:
  - name: abuseipdb-reporter-script
    files: [reporter.py]
generatorOptions:
  disableNameSuffixHash: false   # rev the CM name on script change -> CronJob picks it up
