---
# Local access (HTTP)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: omnitools
  labels:
    app: omnitools
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "OmniTools"
    gethomepage.dev/description: "Self-hosted utility toolbox"
    gethomepage.dev/group: "Home & Tools"
    gethomepage.dev/icon: "omni-tools.png"
    gethomepage.dev/href: "http://omnitools.talos00"
    gethomepage.dev/siteMonitor: "http://omnitools.home-automation.svc.cluster.local:80"
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`omnitools.talos00`)
      services:
        - name: omnitools
          namespace: home-automation
          port: 80
