apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../workload
nameSuffix: -amberdark
patches:
  - target:
      kind: Deployment
      name: external-dns
    patch: |-
      - op: replace
        path: /spec/selector/matchLabels/app.kubernetes.io~1name
        value: external-dns-amberdark
      - op: replace
        path: /spec/template/metadata/labels/app.kubernetes.io~1name
        value: external-dns-amberdark
      - op: replace
        path: /spec/template/spec/containers/0/args/7
        value: --domain-filter=amberdark.net
      - op: replace
        path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
        value: cloudflare-api-token-amberdark
