package main

// Tests for the writing half: normalisation, prettier equivalence, atomic writes, and the
// status semantics `docsgen check` is built on.
//
// The property under test is narrow and load-bearing: generated bytes must be a PRETTIER FIXED
// POINT and a function of the TREE ALONE. If either fails, `docsgen check` starts reporting
// drift it produced itself, and a gate that cries wolf is switched off within a week — at which
// point the generator has made the docs less trustworthy than leaving them hand-written.
//
// Nothing here asserts a date, a commit SHA, or how many components the repo has today. All
// three move under unrelated commits, so baking one in would guarantee a red build that says
// nothing about this code. Structural properties only.

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"
)

// --- normalisation ------------------------------------------------------------------------

// Idempotence is the whole contract between `generate` and `check`: check compares on-disk bytes
// against a freshly normalised render, so if normalising twice ever differed from normalising
// once, the gate would flag the file the generator had just written.
func TestNormalizeMarkdownIsIdempotent(t *testing.T) {
	cases := map[string]string{
		"table":           "# H\n\n| a | bbbb |\n| :-- | --: |\n| cc | d |\n\ntail\n",
		"no table":        "# H\n\nsome prose with a | pipe in it\n\n- bullet\n",
		"empty":           "",
		"whitespace only": "   \n\t\n  \t  \n",
		"crlf":            "# H\r\n\r\n| a | b |\r\n| --- | --- |\r\n| c | d |\r\n",
		"ragged table":    "| a | b | c |\n| --- | --- | --- |\n| x |\n",
	}
	for name, in := range cases {
		t.Run(name, func(t *testing.T) {
			once := normalizeMarkdown(in)
			twice := normalizeMarkdown(once)
			if once != twice {
				t.Errorf("not idempotent\n once: %q\ntwice: %q", once, twice)
			}
		})
	}
}

// The canonical-bytes guarantees the check gate assumes. CRLF is how a doc acquires a diff that
// no human authored, and "exactly one trailing newline" is what keeps the file from fighting
// both prettier and the editor's save hook.
//
// Deliberately silent on how trailing whitespace inside a line is handled: two trailing spaces
// are a markdown hard line break, so that rule is under revision and pinning it here would
// cement whichever answer happens to be current.
func TestNormalizeMarkdownCanonicalBytes(t *testing.T) {
	cases := []struct {
		name, in, want string
	}{
		{"crlf becomes lf", "# H\r\n\r\nbody\r\n", "# H\n\nbody\n"},
		{"missing final newline is added", "# H", "# H\n"},
		{"repeated trailing newlines collapse to one", "# H\n\n\n\n", "# H\n"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := normalizeMarkdown(tc.in); got != tc.want {
				t.Errorf("got %q, want %q", got, tc.want)
			}
		})
	}
}

// --- table layout -------------------------------------------------------------------------

// Every `want` below was captured from prettier 3.9.6 rather than reasoned about, because the
// padding rules are not guessable — the centre case in particular sends the ODD space right,
// which is the opposite of what a naive implementation does. TestPrettierFixedPoint re-proves
// these against the real binary; this test keeps them checkable when prettier is absent.
func TestFormatTablesMatchesPrettierLayout(t *testing.T) {
	cases := []struct {
		name string
		in   []string
		want []string
	}{
		{
			name: "default alignment pads right and floors the separator at the column width",
			in: []string{
				"| a | bbbb |",
				"| --- | --- |",
				"| cc | d |",
			},
			want: []string{
				"| a   | bbbb |",
				"| --- | ---- |",
				"| cc  | d    |",
			},
		},
		{
			// `:--` must keep its colon after widening. Dropping it silently changes how the
			// table renders, and nothing in a diff review makes a lost colon obvious.
			name: "left alignment",
			in: []string{
				"| a | b |",
				"| :-- | --- |",
				"| cc | d |",
			},
			want: []string{
				"| a   | b   |",
				"| :-- | --- |",
				"| cc  | d   |",
			},
		},
		{
			name: "right alignment pads on the left",
			in: []string{
				"| a | b |",
				"| --: | --- |",
				"| cc | d |",
			},
			want: []string{
				"|   a | b   |",
				"| --: | --- |",
				"|  cc | d   |",
			},
		},
		{
			// The odd space goes RIGHT: "abc" in a 4-wide centred column is "abc ", not " abc".
			// Getting this backwards costs one byte per row and the file churns forever.
			name: "centre alignment sends the odd space right",
			in: []string{
				"| head | b |",
				"| :-: | --- |",
				"| abc | d |",
			},
			want: []string{
				"| head | b   |",
				"| :--: | --- |",
				"| abc  | d   |",
			},
		},
		{
			// A one-character column still needs `---` in the separator, so the floor is 3 and
			// the DATA cells widen to match it rather than the separator shrinking.
			name: "column narrower than the three-dash separator floor",
			in: []string{
				"| a | b |",
				"| - | - |",
				"| c | d |",
			},
			want: []string{
				"| a   | b   |",
				"| --- | --- |",
				"| c   | d   |",
			},
		},
		{
			// Content wider than the header drives the column width, including the escaped pipe's
			// backslash, which prettier counts as a visible character.
			name: "escaped pipe counts toward the column width",
			in: []string{
				"| left | esc |",
				"| --- | --- |",
				`| a \| b | c |`,
			},
			want: []string{
				"| left   | esc |",
				"| ------ | --- |",
				`| a \| b | c   |`,
			},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := formatTables(tc.in)
			if len(got) != len(tc.want) {
				t.Fatalf("line count: got %d, want %d\ngot:\n%s", len(got), len(tc.want), strings.Join(got, "\n"))
			}
			for i := range got {
				if got[i] != tc.want[i] {
					t.Errorf("line %d:\n got %q\nwant %q", i, got[i], tc.want[i])
				}
			}
		})
	}
}

// Non-table lines must pass through byte-for-byte. A false positive here would rewrite prose
// that merely contains pipes, which is how a formatter earns a reputation for mangling files.
func TestFormatTablesLeavesNonTablesAlone(t *testing.T) {
	in := []string{
		"# Heading",
		"",
		"a | b | c",           // no leading pipe: not a table row
		"| not | a | table |", // table-shaped, but no separator row follows
		"prose",
	}
	got := formatTables(in)
	for i := range in {
		if got[i] != in[i] {
			t.Errorf("line %d rewritten:\n got %q\nwant %q", i, got[i], in[i])
		}
	}
}

func TestIsSeparatorRow(t *testing.T) {
	// A wrong verdict here is silent: formatTables simply declines to format the table, the file
	// is never a prettier fixed point, and nothing reports why.
	cases := map[string]bool{
		"| --- | --- |":       true,
		"| :-- | --: | :-: |": true,
		"| - |":               true,
		"  | --- | --- |  ":   true,
		"| --- | abc |":       false,
		"| a | b |":           false,
		"| :: | --- |":        false,
		"| : | --- |":         false,
		"not a row":           false,
	}
	for line, want := range cases {
		t.Run(line, func(t *testing.T) {
			if got := isSeparatorRow(line); got != want {
				t.Errorf("isSeparatorRow(%q) = %v, want %v", line, got, want)
			}
		})
	}
}

// --- row splitting ------------------------------------------------------------------------

// `\|` is content. Treating it as a delimiter shreds the row into extra cells, which shifts
// every later cell into the wrong column — a corruption that still renders as a valid table.
func TestSplitRow(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want []string
	}{
		{"plain", "| a | b | c |", []string{"a", "b", "c"}},
		{"escaped pipe is content", `| a \| b | c |`, []string{`a \| b`, "c"}},
		{"two escaped pipes in one cell", `| x \| y \| z | c |`, []string{`x \| y \| z`, "c"}},
		{"escaped backslash before a real delimiter", `| a \\ | b |`, []string{`a \\`, "b"}},
		{"surrounding whitespace is trimmed", "|   a   |  b |", []string{"a", "b"}},
		{"ragged row yields fewer cells", "| x |", []string{"x"}},
		{"empty cells are preserved", "| a |  | c |", []string{"a", "", "c"}},
		{
			// A bare pipe inside a code span still splits the cell. That looks like a bug and is
			// not one: GFM only exempts an ESCAPED pipe, and prettier splits here too, so a
			// "fix" that honoured code spans would take the output off the fixed point.
			"unescaped pipe inside a code span still splits", "| `a | b` | c |",
			[]string{"`a", "b`", "c"},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := splitRow(tc.in)
			if len(got) != len(tc.want) {
				t.Fatalf("cell count: got %d %q, want %d %q", len(got), got, len(tc.want), tc.want)
			}
			for i := range got {
				if got[i] != tc.want[i] {
					t.Errorf("cell %d: got %q, want %q", i, got[i], tc.want[i])
				}
			}
		})
	}
}

// --- prettier equivalence ------------------------------------------------------------------

// The reason the normaliser reimplements prettier's table layout at all is so generated files do
// not join the repo's prettier backlog. That claim is only worth anything if it is executed
// against the real binary, so this test runs prettier exactly the way `task dev:lint:prettier`
// does — from the repo root, with ambient config resolution — and requires the bytes back
// unchanged.
//
// It SKIPS when prettier is absent. A test that hard-fails on a missing tool gets deleted rather
// than fixed, and then the equivalence claim has no test at all.
func TestPrettierFixedPoint(t *testing.T) {
	bin, err := exec.LookPath("prettier")
	if err != nil {
		t.Skip("prettier not on PATH; run under `direnv exec .` to execute this test")
	}
	root := repoRootForTest(t)

	docs := map[string]string{
		"alignment matrix": normalizeMarkdown(strings.Join([]string{
			"# Tables",
			"",
			"| default | left | right | centre |",
			"| --- | :-- | --: | :-: |",
			"| a | bb | ccc | dddd |",
			"| eeeee | f | g | h |",
			"",
			"| tiny | x |",
			"| - | - |",
			"| y | z |",
			"",
		}, "\n")),
		"generated shape": normalizeMarkdown(strings.Join([]string{
			"---",
			"type: reference",
			"status: current",
			"covers:",
			"  - cluster",
			"---",
			"",
			"# Title",
			"",
			"> Generated file — do not edit by hand.",
			"> Second banner line.",
			"",
			"Prose that mentions `backticks` and a literal pipe in a table below.",
			"",
			"| slug | path | nested |",
			"| --- | --- | --- |",
			"| `a` | `infrastructure/base/a` | 0 |",
			"| `longer-slug` | `infrastructure/base/longer/nested/path` | 12 |",
			"",
			"## Related Issues",
			"",
			"- TALOS-f0sd — a ticket",
			"",
		}, "\n")),
		"real component inventory": normalizeMarkdown(renderComponentInventory(realCtx(t))),
	}

	for name, doc := range docs {
		t.Run(name, func(t *testing.T) {
			cmd := exec.Command(bin, "--stdin-filepath",
				filepath.Join(root, "docs", "07-reference", "docsgen-prettier-probe.md"))
			cmd.Dir = root
			cmd.Stdin = strings.NewReader(doc)
			var stdout, stderr bytes.Buffer
			cmd.Stdout = &stdout
			cmd.Stderr = &stderr
			if err := cmd.Run(); err != nil {
				t.Fatalf("prettier failed: %v\n%s", err, stderr.String())
			}
			if got := stdout.String(); got != doc {
				t.Errorf("prettier rewrote the output — it is not a fixed point\n%s",
					firstDifference(doc, got))
			}
		})
	}
}

// firstDifference reports the first line that moved. A whole-document diff of the inventory is
// unreadable, and a padding or ordering bug is always visible in a single line.
func firstDifference(want, got string) string {
	w := strings.Split(want, "\n")
	g := strings.Split(got, "\n")
	for i := 0; i < len(w) && i < len(g); i++ {
		if w[i] != g[i] {
			return "line " + strconv.Itoa(i+1) + ":\n    ours: " + strconv.Quote(w[i]) +
				"\n   other: " + strconv.Quote(g[i])
		}
	}
	return "line counts differ: ours " + strconv.Itoa(len(w)) + ", other " + strconv.Itoa(len(g))
}

// --- writeAtomic --------------------------------------------------------------------------

func TestWriteAtomic(t *testing.T) {
	// An artifact's directory may not exist yet on a fresh clone or after a docs restructure; a
	// generator that refuses to create it is a generator nobody can run the first time.
	t.Run("creates missing parent directories", func(t *testing.T) {
		abs := filepath.Join(t.TempDir(), "a", "b", "c", "doc.md")
		if err := writeAtomic(abs, "hello\n"); err != nil {
			t.Fatalf("writeAtomic: %v", err)
		}
		if b, err := os.ReadFile(abs); err != nil || string(b) != "hello\n" {
			t.Fatalf("content = %q, err = %v", b, err)
		}
	})

	// CreateTemp makes 0600. Renaming that into place would leave a generated, git-tracked doc
	// readable only by the user who happened to run the generator, and the mode difference shows
	// up as a spurious change on the next machine to regenerate it.
	t.Run("result is 0644, not CreateTemp's 0600", func(t *testing.T) {
		abs := filepath.Join(t.TempDir(), "doc.md")
		if err := writeAtomic(abs, "x\n"); err != nil {
			t.Fatalf("writeAtomic: %v", err)
		}
		fi, err := os.Stat(abs)
		if err != nil {
			t.Fatalf("stat: %v", err)
		}
		if got := fi.Mode().Perm(); got != 0o644 {
			t.Errorf("mode = %04o, want 0644", got)
		}
	})

	// The temp file lives in the TARGET directory so the rename stays atomic. That puts it next
	// to tracked files, so a leaked one shows up in `git status` and in the repo's own linters.
	t.Run("leaves no temp residue on success", func(t *testing.T) {
		dir := t.TempDir()
		if err := writeAtomic(filepath.Join(dir, "doc.md"), "x\n"); err != nil {
			t.Fatalf("writeAtomic: %v", err)
		}
		entries, err := os.ReadDir(dir)
		if err != nil {
			t.Fatalf("readdir: %v", err)
		}
		for _, e := range entries {
			if strings.HasPrefix(e.Name(), ".docsgen-") {
				t.Errorf("temp file left behind: %s", e.Name())
			}
		}
		if len(entries) != 1 {
			t.Errorf("directory holds %d entries, want exactly the written file", len(entries))
		}
	})

	// Rename over an existing file must replace it wholesale. A partial overwrite would leave the
	// tail of the previous, longer revision behind — still valid markdown, silently wrong.
	t.Run("overwrites existing content wholesale", func(t *testing.T) {
		abs := filepath.Join(t.TempDir(), "doc.md")
		if err := writeAtomic(abs, "a much longer first revision\n"); err != nil {
			t.Fatalf("first write: %v", err)
		}
		if err := writeAtomic(abs, "short\n"); err != nil {
			t.Fatalf("second write: %v", err)
		}
		b, err := os.ReadFile(abs)
		if err != nil {
			t.Fatalf("read: %v", err)
		}
		if string(b) != "short\n" {
			t.Errorf("content = %q, want %q", b, "short\n")
		}
	})
}

// --- Generate status semantics ---------------------------------------------------------------

// Artifacts() is hardcoded, so there is no seam to inject a stub artifact through. Ctx.Root is
// the seam that matters anyway: pointing it at a temp dir makes the real renderer write into a
// scratch tree, which exercises the genuine artifact without touching docs/.
func tempCtx(t *testing.T) *Ctx {
	t.Helper()
	return &Ctx{Root: t.TempDir(), Cfg: &Config{}, BySlug: map[string]Component{}}
}

func statusOf(t *testing.T, results []GenResult, rel string) GenStatus {
	t.Helper()
	for _, r := range results {
		if r.Rel == rel {
			return r.Status
		}
	}
	t.Fatalf("no result for %q in %+v", rel, results)
	return ""
}

// The Rel is read from Artifacts() rather than spelled out, so renaming the artifact does not
// break tests that are about status semantics.
func firstArtifactRel(t *testing.T) string {
	t.Helper()
	arts := Artifacts()
	if len(arts) == 0 {
		t.Fatal("Artifacts() is empty; nothing to exercise")
	}
	return arts[0].Rel
}

func TestGenerateStatuses(t *testing.T) {
	rel := firstArtifactRel(t)

	t.Run("first run creates the file", func(t *testing.T) {
		ctx := tempCtx(t)
		results, err := Generate(ctx, false)
		if err != nil {
			t.Fatalf("Generate: %v", err)
		}
		if got := statusOf(t, results, rel); got != StatusCreated {
			t.Errorf("status = %q, want %q", got, StatusCreated)
		}
		if !fileExists(filepath.Join(ctx.Root, rel)) {
			t.Errorf("%s was not written", rel)
		}
	})

	// This is the steady state, and the one that must not churn: an unchanged artifact leaves the
	// file completely alone. mtime is checked via an explicitly backdated stamp rather than a
	// before/after comparison, because a rewrite inside the same filesystem timestamp tick would
	// let a naive comparison pass. A backdated file can only keep its stamp if nothing wrote it.
	t.Run("second run is unchanged and does not touch mtime", func(t *testing.T) {
		ctx := tempCtx(t)
		if _, err := Generate(ctx, false); err != nil {
			t.Fatalf("first Generate: %v", err)
		}
		abs := filepath.Join(ctx.Root, rel)
		backdated := time.Now().Add(-72 * time.Hour).Truncate(time.Second)
		if err := os.Chtimes(abs, backdated, backdated); err != nil {
			t.Fatalf("chtimes: %v", err)
		}

		results, err := Generate(ctx, false)
		if err != nil {
			t.Fatalf("second Generate: %v", err)
		}
		if got := statusOf(t, results, rel); got != StatusUnchanged {
			t.Errorf("status = %q, want %q", got, StatusUnchanged)
		}
		fi, err := os.Stat(abs)
		if err != nil {
			t.Fatalf("stat: %v", err)
		}
		if !fi.ModTime().Equal(backdated) {
			t.Errorf("mtime moved to %v (was %v) — the file was rewritten", fi.ModTime(), backdated)
		}
	})

	// A hand edit to a generated file is the case the gate exists for: someone fixes a typo in
	// the table and the next regeneration would silently revert it.
	t.Run("rewrite after drift reports written, not created", func(t *testing.T) {
		ctx := tempCtx(t)
		if _, err := Generate(ctx, false); err != nil {
			t.Fatalf("first Generate: %v", err)
		}
		abs := filepath.Join(ctx.Root, rel)
		if err := os.WriteFile(abs, []byte("hand edited\n"), 0o644); err != nil {
			t.Fatalf("hand edit: %v", err)
		}
		results, err := Generate(ctx, false)
		if err != nil {
			t.Fatalf("second Generate: %v", err)
		}
		if got := statusOf(t, results, rel); got != StatusWritten {
			t.Errorf("status = %q, want %q", got, StatusWritten)
		}
		b, err := os.ReadFile(abs)
		if err != nil {
			t.Fatalf("read: %v", err)
		}
		if string(b) == "hand edited\n" {
			t.Error("the hand edit survived; generate mode did not rewrite the artifact")
		}
	})

	// Missing and drift are distinct exit reasons for a human reading CI output: "never generated"
	// points at the bootstrap step, "drift" points at an edit.
	t.Run("check reports missing and creates nothing", func(t *testing.T) {
		ctx := tempCtx(t)
		results, err := Generate(ctx, true)
		if err != nil {
			t.Fatalf("Generate: %v", err)
		}
		if got := statusOf(t, results, rel); got != StatusMissing {
			t.Errorf("status = %q, want %q", got, StatusMissing)
		}
		if fileExists(filepath.Join(ctx.Root, rel)) {
			t.Errorf("check mode created %s", rel)
		}
	})

	t.Run("check reports drift and leaves the edit in place", func(t *testing.T) {
		ctx := tempCtx(t)
		if _, err := Generate(ctx, false); err != nil {
			t.Fatalf("Generate: %v", err)
		}
		abs := filepath.Join(ctx.Root, rel)
		const edited = "hand edited\n"
		if err := os.WriteFile(abs, []byte(edited), 0o644); err != nil {
			t.Fatalf("hand edit: %v", err)
		}
		results, err := Generate(ctx, true)
		if err != nil {
			t.Fatalf("Generate check: %v", err)
		}
		if got := statusOf(t, results, rel); got != StatusDrift {
			t.Errorf("status = %q, want %q", got, StatusDrift)
		}
		b, err := os.ReadFile(abs)
		if err != nil {
			t.Fatalf("read: %v", err)
		}
		if string(b) != edited {
			t.Error("check mode wrote to the file; it must be read-only")
		}
	})

	// `docsgen check` runs in CI and in pre-commit, where a write would either dirty the tree or
	// paper over the very drift it is meant to report.
	t.Run("check never touches an already-current file", func(t *testing.T) {
		ctx := tempCtx(t)
		if _, err := Generate(ctx, false); err != nil {
			t.Fatalf("Generate: %v", err)
		}
		abs := filepath.Join(ctx.Root, rel)
		backdated := time.Now().Add(-72 * time.Hour).Truncate(time.Second)
		if err := os.Chtimes(abs, backdated, backdated); err != nil {
			t.Fatalf("chtimes: %v", err)
		}
		results, err := Generate(ctx, true)
		if err != nil {
			t.Fatalf("Generate check: %v", err)
		}
		if got := statusOf(t, results, rel); got != StatusUnchanged {
			t.Errorf("status = %q, want %q", got, StatusUnchanged)
		}
		fi, err := os.Stat(abs)
		if err != nil {
			t.Fatalf("stat: %v", err)
		}
		if !fi.ModTime().Equal(backdated) {
			t.Error("check mode moved the mtime")
		}
	})
}

// Generate must report one result per artifact even when they all no-op, because reportGenerate
// prints that list and a silently dropped artifact looks exactly like a passing gate.
func TestGenerateReportsEveryArtifact(t *testing.T) {
	ctx := tempCtx(t)
	results, err := Generate(ctx, true)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if len(results) != len(Artifacts()) {
		t.Errorf("got %d results for %d artifacts", len(results), len(Artifacts()))
	}
}

// --- determinism ----------------------------------------------------------------------------

var (
	realCtxOnce sync.Once
	realCtxVal  *Ctx
	realCtxRoot string
)

// The real repo is used READ-ONLY, and built once: Build shells out to git log over the whole
// history, which is not something to repeat per subtest.
func realCtx(t *testing.T) *Ctx {
	t.Helper()
	realCtxOnce.Do(func() {
		root := RepoRoot(".")
		cfg, err := LoadConfig(".")
		if err != nil {
			return
		}
		realCtxRoot = root
		realCtxVal = Build(root, cfg)
	})
	if realCtxVal == nil {
		t.Skip("could not build a Ctx against the real repo (git or config.yaml unavailable)")
	}
	return realCtxVal
}

func repoRootForTest(t *testing.T) string {
	t.Helper()
	realCtx(t)
	return realCtxRoot
}

// Byte-identical repeat renders are what makes "two consecutive runs produce no diff" true. The
// known way to lose this is an unstable sort: two components can share a slug, and sort.Slice is
// not stable, so equal-slug rows swap between runs unless the comparator is a total order.
func TestRenderComponentInventoryIsDeterministic(t *testing.T) {
	ctx := realCtx(t)
	first := renderComponentInventory(ctx)
	second := renderComponentInventory(ctx)
	if first != second {
		t.Errorf("two renders differ:\n%s", firstDifference(first, second))
	}
	// Structural, not numeric: asserting a component count would bake today's cluster into a unit
	// test and go red on the next unrelated manifest commit.
	if !strings.HasPrefix(first, "---\n") {
		t.Error("output does not open with frontmatter")
	}
	if !strings.Contains(first, "\n# Component Inventory\n") {
		t.Error("output has no H1")
	}
	if !strings.HasSuffix(strings.TrimRight(first, "\n"), "the generator and its whole-file artifacts") {
		t.Error("output does not end with the required Related Issues footer")
	}
}

// Rendering must not reorder or otherwise mutate ctx.Components, because every other consumer
// reads the same slice and an in-place sort here would change their output too.
func TestRenderComponentInventoryDoesNotMutateCtx(t *testing.T) {
	ctx := realCtx(t)
	before := append([]Component(nil), ctx.Components...)
	renderComponentInventory(ctx)
	if len(ctx.Components) != len(before) {
		t.Fatalf("component count changed: %d -> %d", len(before), len(ctx.Components))
	}
	for i := range before {
		if !reflect.DeepEqual(ctx.Components[i], before[i]) {
			t.Fatalf("ctx.Components[%d] mutated: %+v -> %+v", i, before[i], ctx.Components[i])
		}
	}
}

// --- slugFor --------------------------------------------------------------------------------

// The slug is the handle `covers:` resolves through, so a collapsed or unstable slug is invisible
// corruption: BySlug keeps the last writer and every colocation and staleness verdict for that
// slug then describes a different component, with nothing reporting it.
func TestSlugFor(t *testing.T) {
	doc := func(name string) fluxDoc {
		var fd fluxDoc
		fd.Kind = "Kustomization"
		fd.Metadata.Name = name
		return fd
	}
	cases := []struct {
		name     string
		slugFrom string
		base     string
		metaName string
		inFile   int
		want     string
	}{
		{
			// The filename is preferred because metadata.name drifts from it in this repo, and a
			// handle that moves when someone edits a field is not a handle.
			name: "single Kustomization uses the filename", base: "external-secrets",
			metaName: "external-secrets-operator", inFile: 1, want: "external-secrets",
		},
		{
			// The moment one file declares two, the filename identifies two things and both rows
			// collapse onto one map key. metadata.name is what restores uniqueness.
			name: "multi Kustomization file uses metadata.name", base: "external-secrets",
			metaName: "external-secrets-operator", inFile: 2, want: "external-secrets-operator",
		},
		{
			name: "slug_from metadata.name overrides the filename", slugFrom: "metadata.name",
			base: "external-secrets", metaName: "external-secrets-operator", inFile: 1,
			want: "external-secrets-operator",
		},
		{
			// A manifest with no metadata.name must still produce a usable handle rather than an
			// empty-string slug that silently matches nothing.
			name: "empty metadata.name falls back to the filename", base: "kube-system",
			metaName: "", inFile: 1, want: "kube-system",
		},
		{
			name: "empty metadata.name in a multi-doc file falls back to the filename",
			base: "kube-system", metaName: "", inFile: 3, want: "kube-system",
		},
		{
			name:     "slug_from metadata.name with no name falls back to the filename",
			slugFrom: "metadata.name", base: "kube-system", metaName: "", inFile: 1,
			want: "kube-system",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			cfg := &Config{Components: ComponentSource{SlugFrom: tc.slugFrom}}
			if got := slugFor(cfg, tc.base, doc(tc.metaName), tc.inFile); got != tc.want {
				t.Errorf("slugFor = %q, want %q", got, tc.want)
			}
		})
	}
}
