package main

// Tests for the writing half: normalisation, prettier equivalence, atomic writes, and the
// status semantics `docsgen check` is built on.
//
// The property under test is narrow and load-bearing: generated bytes must be a PRETTIER FIXED
// POINT and a function of the TREE ALONE. If either fails, `docsgen check` starts reporting
// drift it produced itself, and a gate that cries wolf is switched off within a week — at which
// point the generator has made the docs less trustworthy than leaving them hand-written.
//
// Nothing here asserts a date, a commit SHA, or how many components the repo has today. All
// three move under unrelated commits, so baking one in would guarantee a red build that says
// nothing about this code. Structural properties only.

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"
)

// --- normalisation ------------------------------------------------------------------------

// Idempotence is the whole contract between `generate` and `check`: check compares on-disk bytes
// against a freshly normalised render, so if normalising twice ever differed from normalising
// once, the gate would flag the file the generator had just written.
func TestNormalizeMarkdownIsIdempotent(t *testing.T) {
	// `empty` and `whitespace only` deliberately do NOT live here. Idempotence is satisfied by
	// BOTH "" and "\n", so a mutation deleting the `if body == ""` guard left this test green
	// while reinstating the one-byte file prettier and docsgen can never agree on. They are
	// asserted as exact bytes in TestNormalizeMarkdownCanonicalBytes instead, which is the only
	// assertion shape that can tell the two apart.
	cases := map[string]string{
		"table":        "# H\n\n| a | bbbb |\n| :-- | --: |\n| cc | d |\n\ntail\n",
		"no table":     "# H\n\nsome prose with a | pipe in it\n\n- bullet\n",
		"crlf":         "# H\r\n\r\n| a | b |\r\n| --- | --- |\r\n| c | d |\r\n",
		"ragged table": "| a | b | c |\n| --- | --- | --- |\n| x |\n",
	}
	for name, in := range cases {
		t.Run(name, func(t *testing.T) {
			once := normalizeMarkdown(in)
			twice := normalizeMarkdown(once)
			if once != twice {
				t.Errorf("not idempotent\n once: %q\ntwice: %q", once, twice)
			}
		})
	}
}

// The canonical-bytes guarantees the check gate assumes. CRLF is how a doc acquires a diff that
// no human authored, and "exactly one trailing newline" is what keeps the file from fighting
// both prettier and the editor's save hook.
//
// Deliberately silent on how trailing whitespace inside a line is handled: two trailing spaces
// are a markdown hard line break, so that rule is under revision and pinning it here would
// cement whichever answer happens to be current.
func TestNormalizeMarkdownCanonicalBytes(t *testing.T) {
	cases := []struct {
		name, in, want string
	}{
		{"crlf becomes lf", "# H\r\n\r\nbody\r\n", "# H\n\nbody\n"},
		{"missing final newline is added", "# H", "# H\n"},
		{"repeated trailing newlines collapse to one", "# H\n\n\n\n", "# H\n"},
		// The empty-document invariant, asserted as BYTES because that is the only way to see
		// it. The unconditional `+ "\n"` tail turned "" into "\n", which prettier deletes on
		// sight — a one-byte file the two tools rewrite past each other forever, and the only
		// drift `docsgen check` can report with nothing to show.
		{"an empty document stays empty rather than becoming a lone newline", "", ""},
		{"a whitespace-only document also collapses to empty", "   \n\t\n  \t  \n", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := normalizeMarkdown(tc.in); got != tc.want {
				t.Errorf("got %q, want %q", got, tc.want)
			}
		})
	}
}

// --- table layout -------------------------------------------------------------------------

// Every `want` below was captured from prettier 3.9.6 rather than reasoned about, because the
// padding rules are not guessable — the centre case in particular sends the ODD space right,
// which is the opposite of what a naive implementation does. TestPrettierFixedPoint re-proves
// these against the real binary; this test keeps them checkable when prettier is absent.
func TestFormatTablesMatchesPrettierLayout(t *testing.T) {
	cases := []struct {
		name string
		in   []string
		want []string
	}{
		{
			name: "default alignment pads right and floors the separator at the column width",
			in: []string{
				"| a | bbbb |",
				"| --- | --- |",
				"| cc | d |",
			},
			want: []string{
				"| a   | bbbb |",
				"| --- | ---- |",
				"| cc  | d    |",
			},
		},
		{
			// `:--` must keep its colon after widening. Dropping it silently changes how the
			// table renders, and nothing in a diff review makes a lost colon obvious.
			name: "left alignment",
			in: []string{
				"| a | b |",
				"| :-- | --- |",
				"| cc | d |",
			},
			want: []string{
				"| a   | b   |",
				"| :-- | --- |",
				"| cc  | d   |",
			},
		},
		{
			name: "right alignment pads on the left",
			in: []string{
				"| a | b |",
				"| --: | --- |",
				"| cc | d |",
			},
			want: []string{
				"|   a | b   |",
				"| --: | --- |",
				"|  cc | d   |",
			},
		},
		{
			// The odd space goes RIGHT: "abc" in a 4-wide centred column is "abc ", not " abc".
			// Getting this backwards costs one byte per row and the file churns forever.
			name: "centre alignment sends the odd space right",
			in: []string{
				"| head | b |",
				"| :-: | --- |",
				"| abc | d |",
			},
			want: []string{
				"| head | b   |",
				"| :--: | --- |",
				"| abc  | d   |",
			},
		},
		{
			// A one-character column still needs `---` in the separator, so the floor is 3 and
			// the DATA cells widen to match it rather than the separator shrinking.
			name: "column narrower than the three-dash separator floor",
			in: []string{
				"| a | b |",
				"| - | - |",
				"| c | d |",
			},
			want: []string{
				"| a   | b   |",
				"| --- | --- |",
				"| c   | d   |",
			},
		},
		{
			// Content wider than the header drives the column width, including the escaped pipe's
			// backslash, which prettier counts as a visible character.
			name: "escaped pipe counts toward the column width",
			in: []string{
				"| left | esc |",
				"| --- | --- |",
				`| a \| b | c |`,
			},
			want: []string{
				"| left   | esc |",
				"| ------ | --- |",
				`| a \| b | c   |`,
			},
		},
		{
			// THE EM-DASH BUG, made a test. An em dash is three BYTES and one display COLUMN.
			// Measuring it with len() padded this column to 7 while prettier padded it to 5,
			// after which `task dev:lint:prettier` and `task docs:check` rewrote the file past
			// each other on every run. `want` below is the literal output of prettier 3.9.6.
			name: "an em dash is one display column, not its three bytes",
			in: []string{
				"| head | b |",
				"| --- | --- |",
				"| a — b | c |",
			},
			want: []string{
				"| head  | b   |",
				"| ----- | --- |",
				"| a — b | c   |",
			},
		},
		{
			// The other half of the same measurement: East Asian Wide characters are ONE rune
			// and TWO columns. len() says nine bytes and a width function without the UAX #11
			// table says three; prettier says six, and only six lays the table out as shown.
			name: "CJK characters are two display columns each",
			in: []string{
				"| head | b |",
				"| --- | --- |",
				"| 日本語 | c |",
			},
			want: []string{
				"| head   | b   |",
				"| ------ | --- |",
				"| 日本語 | c   |",
			},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := formatTables(tc.in)
			if len(got) != len(tc.want) {
				t.Fatalf("line count: got %d, want %d\ngot:\n%s", len(got), len(tc.want), strings.Join(got, "\n"))
			}
			for i := range got {
				if got[i] != tc.want[i] {
					t.Errorf("line %d:\n got %q\nwant %q", i, got[i], tc.want[i])
				}
			}
		})
	}
}

// Non-table lines must pass through byte-for-byte. A false positive here would rewrite prose
// that merely contains pipes, which is how a formatter earns a reputation for mangling files.
func TestFormatTablesLeavesNonTablesAlone(t *testing.T) {
	in := []string{
		"# Heading",
		"",
		"a | b | c",           // no leading pipe: not a table row
		"| not | a | table |", // table-shaped, but no separator row follows
		"prose",
	}
	got := formatTables(in)
	for i := range in {
		if got[i] != in[i] {
			t.Errorf("line %d rewritten:\n got %q\nwant %q", i, got[i], in[i])
		}
	}
}

// --- fenced code blocks ----------------------------------------------------------------------

// A table shown as an EXAMPLE inside a fence is documentation, not content. Reformatting it
// rewrites what the reader is being shown, and the damage is invisible to a fixed-point test
// because prettier leaves fences alone and so both sides are individually stable.
//
// Each case asserts BYTE-IDENTICAL passthrough of a deliberately badly-laid-out table. That is
// the only assertion shape that can tell "the fence was honoured" from "the table happened to
// already be canonical".
func TestFormatTablesRespectsFences(t *testing.T) {
	cases := []struct {
		name string
		in   []string
	}{
		{
			// The base case the whole state machine exists for.
			name: "a table inside a plain fence is left exactly as written",
			in: []string{
				"# H",
				"",
				"```",
				"| a | bbbb |",
				"| --- | --- |",
				"| cc | d |",
				"```",
				"",
				"tail",
			},
		},
		{
			// A closer must repeat the OPENER's character AT LEAST as many times. Without the
			// `n < f.count` half of that rule the inner ``` closes the ```` fence three lines
			// early and the second table — still inside the block a reader sees — is rewritten.
			name: "a ```` fence is not closed by an inner ```",
			in: []string{
				"````",
				"| a | bbbb |",
				"| --- | --- |",
				"| cc | d |",
				"```",
				"| x | yyyy |",
				"| --- | --- |",
				"| zz | w |",
				"````",
			},
		},
		{
			// The other half: a closer carries NO info string. Without that check a ```go line
			// inside a plain fence closes it immediately and everything after it is treated as
			// live document content.
			//
			// This one is deliberately NOT in TestPrettierFixedPoint: prettier widens the fence
			// to ```` so the inner ``` cannot be mistaken for a closer, which is a rewrite of
			// the fence rather than of the table. Declining to touch the block is still the
			// correct behaviour here — see "Known limitations" in README.md.
			name: "a plain fence is not closed by a ```go line",
			in: []string{
				"```",
				"| a | bbbb |",
				"| --- | --- |",
				"| cc | d |",
				"```go",
				"| x | yyyy |",
				"| --- | --- |",
				"| zz | w |",
				"```",
			},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := formatTables(tc.in)
			if len(got) != len(tc.in) {
				t.Fatalf("line count: got %d, want %d\ngot:\n%s", len(got), len(tc.in), strings.Join(got, "\n"))
			}
			for i := range got {
				if got[i] != tc.in[i] {
					t.Errorf("line %d rewritten inside a fence:\n got %q\nwant %q", i, got[i], tc.in[i])
				}
			}
		})
	}
}

// --- indentation -------------------------------------------------------------------------------

// Indent decides two separate questions, and both are load-bearing:
//
//   - HOW MANY columns of it there are decides whether the block is a table at all, because
//     four columns is an indented code block in markdown and reformatting one changes what the
//     reader sees rather than how it is laid out.
//   - WHICH bytes they are decides where the rewritten table is emitted, because a table nested
//     in a list item that comes back at column zero has been torn out of its list.
func TestFormatTablesIndentHandling(t *testing.T) {
	cases := []struct {
		name string
		in   []string
		want []string
	}{
		{
			// Two columns is still a table, and it must come back at two columns. `want` is the
			// literal output of prettier 3.9.6 on the same list item.
			name: "a table indented two spaces inside a list item keeps its indent",
			in: []string{
				"- item",
				"",
				"  | a | bbbb |",
				"  | --- | --- |",
				"  | cc | d |",
			},
			want: []string{
				"- item",
				"",
				"  | a   | bbbb |",
				"  | --- | ---- |",
				"  | cc  | d    |",
			},
		},
		{
			// Four columns is an INDENTED CODE BLOCK. Laying it out as a table would change the
			// document's meaning, so it passes through byte-identical. Prettier agrees: it
			// leaves this block untouched too.
			name: "a table indented four spaces is an indented code block and is untouched",
			in: []string{
				"    | a | bbbb |",
				"    | --- | --- |",
				"    | cc | d |",
			},
			want: []string{
				"    | a | bbbb |",
				"    | --- | --- |",
				"    | cc | d |",
			},
		},
		{
			// A tab advances to the next multiple of four, so one tab is four columns and this
			// is an indented code block by exactly the same rule. Measuring the indent in RUNES
			// instead would call it one column and reformat a code block.
			//
			// Not a prettier fixed point and deliberately not in TestPrettierFixedPoint:
			// prettier expands the leading tab to four spaces. Leaving the block alone is the
			// conservative half of that disagreement — an untouched block is merely unformatted.
			name: "a tab-indented table is four columns too and is untouched",
			in: []string{
				"\t| a | bbbb |",
				"\t| --- | --- |",
				"\t| cc | d |",
			},
			want: []string{
				"\t| a | bbbb |",
				"\t| --- | --- |",
				"\t| cc | d |",
			},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := formatTables(tc.in)
			if len(got) != len(tc.want) {
				t.Fatalf("line count: got %d, want %d\ngot:\n%s", len(got), len(tc.want), strings.Join(got, "\n"))
			}
			for i := range got {
				if got[i] != tc.want[i] {
					t.Errorf("line %d:\n got %q\nwant %q", i, got[i], tc.want[i])
				}
			}
		})
	}
}

// --- refusal on unstable widths ------------------------------------------------------------

// The refusal is the whole reason normalizeMarkdownChecked exists apart from normalizeMarkdown.
// Prettier measures a cell with a grapheme-aware width library whose answer for a zero-width
// joiner is ONE column, while any "zero-width means zero columns" model says none — so a cell
// containing one is a file prettier repads and docsgen pads back, forever.
//
// A guard with no test can be deleted wholesale and every other spec stays green, because the
// error path is the only observable difference.
func TestNormalizeMarkdownRefusesUnstableWidth(t *testing.T) {
	const zwj = "\u200d"

	t.Run("a cell containing a zero-width joiner is refused", func(t *testing.T) {
		_, err := normalizeMarkdownChecked("| head | b |\n| --- | --- |\n| a" + zwj + "b | c |\n")
		if err == nil {
			t.Fatal("no error; the refusal guard is gone and the artifact will oscillate with prettier")
		}
		// The message must NAME the cell, because the only available fix is a human rewriting
		// that cell and an error that says "somewhere in this document" does not locate it.
		// The cell is quoted with %q, which is what makes an invisible code point visible at
		// all — the raw bytes in a terminal would read as "ab".
		if want := strconv.Quote("a" + zwj + "b"); !strings.Contains(err.Error(), want) {
			t.Errorf("error does not name the offending cell %s: %v", want, err)
		}
		if !strings.Contains(err.Error(), "U+200D") {
			t.Errorf("error does not name the offending code point: %v", err)
		}
	})

	t.Run("a document with no such cell is not refused", func(t *testing.T) {
		if _, err := normalizeMarkdownChecked("| head | b |\n| --- | --- |\n| ab | c |\n"); err != nil {
			t.Errorf("unexpected refusal: %v", err)
		}
	})

	// formatTables discards the error and must still hand back every row — a caller that only
	// wants bytes needs a complete slice, and every row but the offending cell is correct.
	t.Run("the unchecked line-level form still returns every row", func(t *testing.T) {
		in := []string{"| head | b |", "| --- | --- |", "| a" + zwj + "b | c |"}
		if got := formatTables(in); len(got) != len(in) {
			t.Errorf("got %d lines, want %d:\n%s", len(got), len(in), strings.Join(got, "\n"))
		}
	})

	// The DOCUMENT-level unchecked form behaves differently and this pins which: it returns the
	// empty string, because normalizeMarkdownChecked returns ("", err) before the rows reach
	// it. Asserted rather than left implicit, so the two "unchecked" spellings are not assumed
	// to agree — they do not.
	t.Run("the unchecked document-level form yields empty bytes, not a best-effort table", func(t *testing.T) {
		if got := normalizeMarkdown("| head | b |\n| --- | --- |\n| a" + zwj + "b | c |\n"); got != "" {
			t.Errorf("got %q, want the empty string", got)
		}
	})
}

func TestIsSeparatorRow(t *testing.T) {
	// A wrong verdict here is silent: formatTables simply declines to format the table, the file
	// is never a prettier fixed point, and nothing reports why.
	cases := map[string]bool{
		"| --- | --- |":       true,
		"| :-- | --: | :-: |": true,
		"| - |":               true,
		"  | --- | --- |  ":   true,
		"| --- | abc |":       false,
		"| a | b |":           false,
		"| :: | --- |":        false,
		"| : | --- |":         false,
		"not a row":           false,
	}
	for line, want := range cases {
		t.Run(line, func(t *testing.T) {
			if got := isSeparatorRow(line); got != want {
				t.Errorf("isSeparatorRow(%q) = %v, want %v", line, got, want)
			}
		})
	}
}

// --- row splitting ------------------------------------------------------------------------

// `\|` is content. Treating it as a delimiter shreds the row into extra cells, which shifts
// every later cell into the wrong column — a corruption that still renders as a valid table.
func TestSplitRow(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want []string
	}{
		{"plain", "| a | b | c |", []string{"a", "b", "c"}},
		{"escaped pipe is content", `| a \| b | c |`, []string{`a \| b`, "c"}},
		{"two escaped pipes in one cell", `| x \| y \| z | c |`, []string{`x \| y \| z`, "c"}},
		{"escaped backslash before a real delimiter", `| a \\ | b |`, []string{`a \\`, "b"}},
		{"surrounding whitespace is trimmed", "|   a   |  b |", []string{"a", "b"}},
		{"ragged row yields fewer cells", "| x |", []string{"x"}},
		{"empty cells are preserved", "| a |  | c |", []string{"a", "", "c"}},
		{
			// A bare pipe inside a code span still splits the cell. That looks like a bug and is
			// not one: GFM only exempts an ESCAPED pipe, and prettier splits here too, so a
			// "fix" that honoured code spans would take the output off the fixed point.
			"unescaped pipe inside a code span still splits", "| `a | b` | c |",
			[]string{"`a", "b`", "c"},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := splitRow(tc.in)
			if len(got) != len(tc.want) {
				t.Fatalf("cell count: got %d %q, want %d %q", len(got), got, len(tc.want), tc.want)
			}
			for i := range got {
				if got[i] != tc.want[i] {
					t.Errorf("cell %d: got %q, want %q", i, got[i], tc.want[i])
				}
			}
		})
	}
}

// --- prettier equivalence ------------------------------------------------------------------

// The reason the normaliser reimplements prettier's table layout at all is so generated files do
// not join the repo's prettier backlog. That claim is only worth anything if it is executed
// against the real binary, so this test runs prettier exactly the way `task dev:lint:prettier`
// does — from the repo root, with ambient config resolution — and requires the bytes back
// unchanged.
//
// It SKIPS when prettier is absent. A test that hard-fails on a missing tool gets deleted rather
// than fixed, and then the equivalence claim has no test at all.
func TestPrettierFixedPoint(t *testing.T) {
	bin, err := exec.LookPath("prettier")
	if err != nil {
		t.Skip("prettier not on PATH; run under `direnv exec .` to execute this test")
	}
	root := repoRootForTest(t)

	docs := map[string]string{
		"alignment matrix": normalizeMarkdown(strings.Join([]string{
			"# Tables",
			"",
			"| default | left | right | centre |",
			"| --- | :-- | --: | :-: |",
			"| a | bb | ccc | dddd |",
			"| eeeee | f | g | h |",
			"",
			"| tiny | x |",
			"| - | - |",
			"| y | z |",
			"",
		}, "\n")),
		"generated shape": normalizeMarkdown(strings.Join([]string{
			"---",
			"type: reference",
			"status: current",
			"covers:",
			"  - cluster",
			"---",
			"",
			"# Title",
			"",
			"> Generated file — do not edit by hand.",
			"> Second banner line.",
			"",
			"Prose that mentions `backticks` and a literal pipe in a table below.",
			"",
			"| slug | path | nested |",
			"| --- | --- | --- |",
			"| `a` | `infrastructure/base/a` | 0 |",
			"| `longer-slug` | `infrastructure/base/longer/nested/path` | 12 |",
			"",
			"## Related Issues",
			"",
			"- TALOS-f0sd — a ticket",
			"",
		}, "\n")),
		// The display-width cases re-proved against the real binary. The layout test above
		// hardcodes prettier 3.9.6's bytes; this is what keeps that capture honest when
		// prettier moves.
		"display width": normalizeMarkdown(strings.Join([]string{
			"# Widths",
			"",
			"| head | b |",
			"| --- | --- |",
			"| a — b | c |",
			"",
			"| head | b |",
			"| --- | --- |",
			"| 日本語 | c |",
			"",
		}, "\n")),
		// Blocks docsgen deliberately does not touch. A fixed point here means "untouched" and
		// "prettier-correct" are the same answer for these shapes, which is the claim the fence
		// and indent tests make in isolation.
		//
		// The ```go-inside-a-plain-fence case and the tab-indented case are absent on purpose:
		// prettier rewrites the FENCE and the INDENT respectively, so neither is a fixed point.
		// Both are covered byte-for-byte in TestFormatTablesRespectsFences and
		// TestFormatTablesIndentHandling.
		"untouched blocks": normalizeMarkdown(strings.Join([]string{
			"# Untouched",
			"",
			"```",
			"| a | bbbb |",
			"| --- | --- |",
			"| cc | d |",
			"```",
			"",
			"````",
			"| a | bbbb |",
			"| --- | --- |",
			"| cc | d |",
			"```",
			"| x | yyyy |",
			"| --- | --- |",
			"| zz | w |",
			"````",
			"",
			"    | a | bbbb |",
			"    | --- | --- |",
			"    | cc | d |",
			"",
			"- item",
			"",
			"  | a | bbbb |",
			"  | --- | --- |",
			"  | cc | d |",
			"",
		}, "\n")),
		"real component inventory": normalizeMarkdown(renderComponentInventory(realCtx(t), realSpec(t))),
	}

	for name, doc := range docs {
		t.Run(name, func(t *testing.T) {
			cmd := exec.Command(bin, "--stdin-filepath",
				filepath.Join(root, "docs", "07-reference", "docsgen-prettier-probe.md"))
			cmd.Dir = root
			cmd.Stdin = strings.NewReader(doc)
			var stdout, stderr bytes.Buffer
			cmd.Stdout = &stdout
			cmd.Stderr = &stderr
			if err := cmd.Run(); err != nil {
				t.Fatalf("prettier failed: %v\n%s", err, stderr.String())
			}
			if got := stdout.String(); got != doc {
				t.Errorf("prettier rewrote the output — it is not a fixed point\n%s",
					firstDifference(doc, got))
			}
		})
	}
}

// firstDifference reports the first line that moved. A whole-document diff of the inventory is
// unreadable, and a padding or ordering bug is always visible in a single line.
func firstDifference(want, got string) string {
	w := strings.Split(want, "\n")
	g := strings.Split(got, "\n")
	for i := 0; i < len(w) && i < len(g); i++ {
		if w[i] != g[i] {
			return "line " + strconv.Itoa(i+1) + ":\n    ours: " + strconv.Quote(w[i]) +
				"\n   other: " + strconv.Quote(g[i])
		}
	}
	return "line counts differ: ours " + strconv.Itoa(len(w)) + ", other " + strconv.Itoa(len(g))
}

// --- writeAtomic --------------------------------------------------------------------------

func TestWriteAtomic(t *testing.T) {
	// An artifact's directory may not exist yet on a fresh clone or after a docs restructure; a
	// generator that refuses to create it is a generator nobody can run the first time.
	t.Run("creates missing parent directories", func(t *testing.T) {
		abs := filepath.Join(t.TempDir(), "a", "b", "c", "doc.md")
		if err := writeAtomic(abs, "hello\n"); err != nil {
			t.Fatalf("writeAtomic: %v", err)
		}
		if b, err := os.ReadFile(abs); err != nil || string(b) != "hello\n" {
			t.Fatalf("content = %q, err = %v", b, err)
		}
	})

	// CreateTemp makes 0600. Renaming that into place would leave a generated, git-tracked doc
	// readable only by the user who happened to run the generator, and the mode difference shows
	// up as a spurious change on the next machine to regenerate it.
	t.Run("result is 0644, not CreateTemp's 0600", func(t *testing.T) {
		abs := filepath.Join(t.TempDir(), "doc.md")
		if err := writeAtomic(abs, "x\n"); err != nil {
			t.Fatalf("writeAtomic: %v", err)
		}
		fi, err := os.Stat(abs)
		if err != nil {
			t.Fatalf("stat: %v", err)
		}
		if got := fi.Mode().Perm(); got != 0o644 {
			t.Errorf("mode = %04o, want 0644", got)
		}
	})

	// The temp file lives in the TARGET directory so the rename stays atomic. That puts it next
	// to tracked files, so a leaked one shows up in `git status` and in the repo's own linters.
	t.Run("leaves no temp residue on success", func(t *testing.T) {
		dir := t.TempDir()
		if err := writeAtomic(filepath.Join(dir, "doc.md"), "x\n"); err != nil {
			t.Fatalf("writeAtomic: %v", err)
		}
		entries, err := os.ReadDir(dir)
		if err != nil {
			t.Fatalf("readdir: %v", err)
		}
		for _, e := range entries {
			if strings.HasPrefix(e.Name(), ".docsgen-") {
				t.Errorf("temp file left behind: %s", e.Name())
			}
		}
		if len(entries) != 1 {
			t.Errorf("directory holds %d entries, want exactly the written file", len(entries))
		}
	})

	// Rename over an existing file must replace it wholesale. A partial overwrite would leave the
	// tail of the previous, longer revision behind — still valid markdown, silently wrong.
	t.Run("overwrites existing content wholesale", func(t *testing.T) {
		abs := filepath.Join(t.TempDir(), "doc.md")
		if err := writeAtomic(abs, "a much longer first revision\n"); err != nil {
			t.Fatalf("first write: %v", err)
		}
		if err := writeAtomic(abs, "short\n"); err != nil {
			t.Fatalf("second write: %v", err)
		}
		b, err := os.ReadFile(abs)
		if err != nil {
			t.Fatalf("read: %v", err)
		}
		if string(b) != "short\n" {
			t.Errorf("content = %q, want %q", b, "short\n")
		}
	})
}

// --- Generate status semantics ---------------------------------------------------------------

// tempCtx builds a Ctx whose root is a scratch tree AND whose config declares a real artifact.
//
// THE CONFIG HALF IS NOT OPTIONAL. Artifacts(cfg) returns the empty set for a config with no
// `artifacts:` block, so a `&Config{}` here would make every status spec below iterate nothing
// and pass while asserting nothing — the exact failure mode this whole change exists to remove,
// reappearing inside the fix for it. firstArtifactRel and TestGenerateReportsEveryArtifact both
// fail loudly on an empty set for the same reason.
//
// The vocabulary is minimal but REAL: the pre-write gate runs the repo's own frontmatter and
// taxonomy rules over the rendered bytes, so a config whose enums did not admit the artifact's
// own front matter would refuse to write and every spec here would fail on the refusal rather
// than on what it meant to assert.
func tempCtx(t *testing.T) *Ctx {
	t.Helper()
	return &Ctx{Root: t.TempDir(), Cfg: tempConfig(), BySlug: map[string]Component{}}
}

func tempConfig() *Config {
	return &Config{
		DocsRoot:       "docs",
		DocTypes:       []string{"reference"},
		Statuses:       []string{"current"},
		Freshness:      []string{"tracks-code"},
		KeyOrder:       []string{"type", "status", "covers", "freshness", "tickets", "bluf"},
		RequiredFooter: "## Related Issues",
		Components:     ComponentSource{Kind: "dirs", Path: "components", Glob: "*"},
		Artifacts: map[string]ArtifactSpec{
			"component-inventory": {
				Path: "07-reference/component-inventory.md",
				Front: map[string]any{
					"type":      "reference",
					"status":    "current",
					"covers":    []any{"cluster"},
					"freshness": "tracks-code",
					"tickets":   []any{"UNIT-1"},
					"bluf":      "the unit layer's stand-in for a real host repository",
				},
				TicketNotes: map[string]string{"UNIT-1": "the unit-layer artifact fixture"},
			},
		},
	}
}

func statusOf(t *testing.T, results []GenResult, rel string) GenStatus {
	t.Helper()
	for _, r := range results {
		if r.Rel == rel {
			return r.Status
		}
	}
	t.Fatalf("no result for %q in %+v", rel, results)
	return ""
}

// The Rel is read from Artifacts(cfg) rather than spelled out, so renaming the artifact — or
// moving the host repo's docs_root — does not break tests that are about status semantics.
func firstArtifactRel(t *testing.T) string {
	t.Helper()
	arts := Artifacts(tempConfig())
	if len(arts) == 0 {
		t.Fatal("no artifacts configured; every status spec below would pass vacuously")
	}
	return arts[0].Rel
}

func TestGenerateStatuses(t *testing.T) {
	rel := firstArtifactRel(t)
	if len(Artifacts(tempConfig())) == 0 {
		t.Fatal("no artifacts configured; this test would pass vacuously")
	}

	t.Run("first run creates the file", func(t *testing.T) {
		ctx := tempCtx(t)
		results, err := Generate(ctx, false)
		if err != nil {
			t.Fatalf("Generate: %v", err)
		}
		if got := statusOf(t, results, rel); got != StatusCreated {
			t.Errorf("status = %q, want %q", got, StatusCreated)
		}
		if !fileExists(filepath.Join(ctx.Root, rel)) {
			t.Errorf("%s was not written", rel)
		}
	})

	// This is the steady state, and the one that must not churn: an unchanged artifact leaves the
	// file completely alone. mtime is checked via an explicitly backdated stamp rather than a
	// before/after comparison, because a rewrite inside the same filesystem timestamp tick would
	// let a naive comparison pass. A backdated file can only keep its stamp if nothing wrote it.
	t.Run("second run is unchanged and does not touch mtime", func(t *testing.T) {
		ctx := tempCtx(t)
		if _, err := Generate(ctx, false); err != nil {
			t.Fatalf("first Generate: %v", err)
		}
		abs := filepath.Join(ctx.Root, rel)
		backdated := time.Now().Add(-72 * time.Hour).Truncate(time.Second)
		if err := os.Chtimes(abs, backdated, backdated); err != nil {
			t.Fatalf("chtimes: %v", err)
		}

		results, err := Generate(ctx, false)
		if err != nil {
			t.Fatalf("second Generate: %v", err)
		}
		if got := statusOf(t, results, rel); got != StatusUnchanged {
			t.Errorf("status = %q, want %q", got, StatusUnchanged)
		}
		fi, err := os.Stat(abs)
		if err != nil {
			t.Fatalf("stat: %v", err)
		}
		if !fi.ModTime().Equal(backdated) {
			t.Errorf("mtime moved to %v (was %v) — the file was rewritten", fi.ModTime(), backdated)
		}
	})

	// A hand edit to a generated file is the case the gate exists for: someone fixes a typo in
	// the table and the next regeneration would silently revert it.
	t.Run("rewrite after drift reports written, not created", func(t *testing.T) {
		ctx := tempCtx(t)
		if _, err := Generate(ctx, false); err != nil {
			t.Fatalf("first Generate: %v", err)
		}
		abs := filepath.Join(ctx.Root, rel)
		if err := os.WriteFile(abs, []byte("hand edited\n"), 0o644); err != nil {
			t.Fatalf("hand edit: %v", err)
		}
		results, err := Generate(ctx, false)
		if err != nil {
			t.Fatalf("second Generate: %v", err)
		}
		if got := statusOf(t, results, rel); got != StatusWritten {
			t.Errorf("status = %q, want %q", got, StatusWritten)
		}
		b, err := os.ReadFile(abs)
		if err != nil {
			t.Fatalf("read: %v", err)
		}
		if string(b) == "hand edited\n" {
			t.Error("the hand edit survived; generate mode did not rewrite the artifact")
		}
	})

	// Missing and drift are distinct exit reasons for a human reading CI output: "never generated"
	// points at the bootstrap step, "drift" points at an edit.
	t.Run("check reports missing and creates nothing", func(t *testing.T) {
		ctx := tempCtx(t)
		results, err := Generate(ctx, true)
		if err != nil {
			t.Fatalf("Generate: %v", err)
		}
		if got := statusOf(t, results, rel); got != StatusMissing {
			t.Errorf("status = %q, want %q", got, StatusMissing)
		}
		if fileExists(filepath.Join(ctx.Root, rel)) {
			t.Errorf("check mode created %s", rel)
		}
	})

	t.Run("check reports drift and leaves the edit in place", func(t *testing.T) {
		ctx := tempCtx(t)
		if _, err := Generate(ctx, false); err != nil {
			t.Fatalf("Generate: %v", err)
		}
		abs := filepath.Join(ctx.Root, rel)
		const edited = "hand edited\n"
		if err := os.WriteFile(abs, []byte(edited), 0o644); err != nil {
			t.Fatalf("hand edit: %v", err)
		}
		results, err := Generate(ctx, true)
		if err != nil {
			t.Fatalf("Generate check: %v", err)
		}
		if got := statusOf(t, results, rel); got != StatusDrift {
			t.Errorf("status = %q, want %q", got, StatusDrift)
		}
		b, err := os.ReadFile(abs)
		if err != nil {
			t.Fatalf("read: %v", err)
		}
		if string(b) != edited {
			t.Error("check mode wrote to the file; it must be read-only")
		}
	})

	// `docsgen check` runs in CI and in pre-commit, where a write would either dirty the tree or
	// paper over the very drift it is meant to report.
	t.Run("check never touches an already-current file", func(t *testing.T) {
		ctx := tempCtx(t)
		if _, err := Generate(ctx, false); err != nil {
			t.Fatalf("Generate: %v", err)
		}
		abs := filepath.Join(ctx.Root, rel)
		backdated := time.Now().Add(-72 * time.Hour).Truncate(time.Second)
		if err := os.Chtimes(abs, backdated, backdated); err != nil {
			t.Fatalf("chtimes: %v", err)
		}
		results, err := Generate(ctx, true)
		if err != nil {
			t.Fatalf("Generate check: %v", err)
		}
		if got := statusOf(t, results, rel); got != StatusUnchanged {
			t.Errorf("status = %q, want %q", got, StatusUnchanged)
		}
		fi, err := os.Stat(abs)
		if err != nil {
			t.Fatalf("stat: %v", err)
		}
		if !fi.ModTime().Equal(backdated) {
			t.Error("check mode moved the mtime")
		}
	})
}

// Generate must report one result per artifact even when they all no-op, because reportGenerate
// prints that list and a silently dropped artifact looks exactly like a passing gate.
func TestGenerateReportsEveryArtifact(t *testing.T) {
	ctx := tempCtx(t)
	// Artifacts(cfg) can legitimately be empty now, and an empty set makes "one result per
	// artifact" trivially true. Guard before asserting, or this spec becomes a tautology the
	// moment somebody drops the `artifacts:` stanza out of tempConfig.
	if len(Artifacts(ctx.Cfg)) == 0 {
		t.Fatal("no artifacts configured; this test would pass vacuously")
	}
	results, err := Generate(ctx, true)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if len(results) != len(Artifacts(ctx.Cfg)) {
		t.Errorf("got %d results for %d artifacts", len(results), len(Artifacts(ctx.Cfg)))
	}
}

// A read that fails for any reason OTHER than "no such file" is an error, never a silent
// "treat it as absent and write anyway". Treating every read failure as absence is the
// documented mode-000 bug: a byte-identical but unreadable artifact reported `missing` under
// check and got REWRITTEN under generate, silently relaxing it to 0644 and breaking the
// write-only-if-changed invariant. A target that is a directory, or one whose parent is
// unwritable, misreported the same way and then failed later with an error about something
// else entirely.
//
// The file is made byte-identical FIRST, so nothing about this case depends on the content
// differing — the only thing that changed is whether the bytes can be read.
func TestGenerateRefusesAnUnreadableArtifact(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("running as root, which reads mode-000 files regardless of permissions")
	}
	rel := firstArtifactRel(t)

	for _, check := range []bool{false, true} {
		mode := "generate"
		if check {
			mode = "check"
		}
		t.Run(mode+" mode returns an error naming the file", func(t *testing.T) {
			ctx := tempCtx(t)
			if _, err := Generate(ctx, false); err != nil {
				t.Fatalf("seeding Generate: %v", err)
			}
			abs := filepath.Join(ctx.Root, rel)
			before, err := os.ReadFile(abs)
			if err != nil {
				t.Fatalf("read back the seeded artifact: %v", err)
			}
			if err := os.Chmod(abs, 0); err != nil {
				t.Fatalf("chmod 0: %v", err)
			}
			t.Cleanup(func() { _ = os.Chmod(abs, 0o644) })

			_, gerr := Generate(ctx, check)

			if gerr == nil {
				t.Fatal("no error; an unreadable artifact was treated as absent, which is the mode-000 bug")
			}
			if !strings.Contains(gerr.Error(), rel) {
				t.Errorf("error does not name the artifact %q: %v", rel, gerr)
			}
			// And it must not have been rewritten on the way past. 0644 here would mean the
			// generator silently relaxed the mode a human deliberately set.
			fi, serr := os.Stat(abs)
			if serr != nil {
				t.Fatalf("stat: %v", serr)
			}
			if got := fi.Mode().Perm(); got != 0 {
				t.Errorf("mode = %04o, want 0000 — the artifact was rewritten", got)
			}
			if err := os.Chmod(abs, 0o644); err != nil {
				t.Fatalf("restore mode: %v", err)
			}
			after, err := os.ReadFile(abs)
			if err != nil {
				t.Fatalf("read back after: %v", err)
			}
			if !bytes.Equal(before, after) {
				t.Error("the artifact's bytes changed; the unreadable file was rewritten")
			}
		})
	}
}

// --- determinism ----------------------------------------------------------------------------

var (
	realCtxOnce sync.Once
	realCtxVal  *Ctx
	realCtxRoot string
)

// The real repo is used READ-ONLY, and built once: Build shells out to git log over the whole
// history, which is not something to repeat per subtest.
func realCtx(t *testing.T) *Ctx {
	t.Helper()
	realCtxOnce.Do(func() {
		root := RepoRoot(".")
		cfg, err := LoadConfig(".")
		if err != nil {
			return
		}
		realCtxRoot = root
		realCtxVal = Build(root, cfg)
	})
	if realCtxVal == nil {
		t.Skip("could not build a Ctx against the real repo (git or config.yaml unavailable)")
	}
	return realCtxVal
}

// realSpec is the host repo's own `artifacts.component-inventory` stanza, read from its config
// rather than reconstructed here. Reconstructing it would let this file and config.yaml drift
// apart, and the determinism spec below would then be proving a property of a stanza nothing
// ships.
func realSpec(t *testing.T) ArtifactSpec {
	t.Helper()
	cfg := realCtx(t).Cfg
	spec, ok := cfg.Artifacts["component-inventory"]
	if !ok {
		t.Fatal("the host config declares no `artifacts.component-inventory`; this spec would " +
			"render an artifact nobody ships")
	}
	return spec
}

func repoRootForTest(t *testing.T) string {
	t.Helper()
	realCtx(t)
	return realCtxRoot
}

// Byte-identical repeat renders are what makes "two consecutive runs produce no diff" true. The
// known way to lose this is an unstable sort: two components can share a slug, and sort.Slice is
// not stable, so equal-slug rows swap between runs unless the comparator is a total order.
func TestRenderComponentInventoryIsDeterministic(t *testing.T) {
	ctx := realCtx(t)
	first := renderComponentInventory(ctx, realSpec(t))
	second := renderComponentInventory(ctx, realSpec(t))
	if first != second {
		t.Errorf("two renders differ:\n%s", firstDifference(first, second))
	}
	// Structural, not numeric: asserting a component count would bake today's cluster into a unit
	// test and go red on the next unrelated manifest commit.
	if !strings.HasPrefix(first, "---\n") {
		t.Error("output does not open with frontmatter")
	}
	if !strings.Contains(first, "\n# Component Inventory\n") {
		t.Error("output has no H1")
	}
	if !strings.HasSuffix(strings.TrimRight(first, "\n"), "the generator and its whole-file artifacts") {
		t.Error("output does not end with the required Related Issues footer")
	}
}

// Rendering must not reorder or otherwise mutate ctx.Components, because every other consumer
// reads the same slice and an in-place sort here would change their output too.
func TestRenderComponentInventoryDoesNotMutateCtx(t *testing.T) {
	ctx := realCtx(t)
	before := append([]Component(nil), ctx.Components...)
	renderComponentInventory(ctx, realSpec(t))
	if len(ctx.Components) != len(before) {
		t.Fatalf("component count changed: %d -> %d", len(before), len(ctx.Components))
	}
	for i := range before {
		if !reflect.DeepEqual(ctx.Components[i], before[i]) {
			t.Fatalf("ctx.Components[%d] mutated: %+v -> %+v", i, before[i], ctx.Components[i])
		}
	}
}

// --- slugFor --------------------------------------------------------------------------------

// The slug is the handle `covers:` resolves through, so a collapsed or unstable slug is invisible
// corruption: BySlug keeps the last writer and every colocation and staleness verdict for that
// slug then describes a different component, with nothing reporting it.
func TestSlugFor(t *testing.T) {
	doc := func(name string) fluxDoc {
		var fd fluxDoc
		fd.Kind = "Kustomization"
		fd.Metadata.Name = name
		return fd
	}
	cases := []struct {
		name     string
		slugFrom string
		base     string
		metaName string
		inFile   int
		want     string
	}{
		{
			// The filename is preferred because metadata.name drifts from it in this repo, and a
			// handle that moves when someone edits a field is not a handle.
			name: "single Kustomization uses the filename", base: "external-secrets",
			metaName: "external-secrets-operator", inFile: 1, want: "external-secrets",
		},
		{
			// The moment one file declares two, the filename identifies two things and both rows
			// collapse onto one map key. metadata.name is what restores uniqueness.
			name: "multi Kustomization file uses metadata.name", base: "external-secrets",
			metaName: "external-secrets-operator", inFile: 2, want: "external-secrets-operator",
		},
		{
			name: "slug_from metadata.name overrides the filename", slugFrom: "metadata.name",
			base: "external-secrets", metaName: "external-secrets-operator", inFile: 1,
			want: "external-secrets-operator",
		},
		{
			// A manifest with no metadata.name must still produce a usable handle rather than an
			// empty-string slug that silently matches nothing.
			name: "empty metadata.name falls back to the filename", base: "kube-system",
			metaName: "", inFile: 1, want: "kube-system",
		},
		{
			name: "empty metadata.name in a multi-doc file falls back to the filename",
			base: "kube-system", metaName: "", inFile: 3, want: "kube-system",
		},
		{
			name:     "slug_from metadata.name with no name falls back to the filename",
			slugFrom: "metadata.name", base: "kube-system", metaName: "", inFile: 1,
			want: "kube-system",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			cfg := &Config{Components: ComponentSource{SlugFrom: tc.slugFrom}}
			if got := slugFor(cfg, tc.base, doc(tc.metaName), tc.inFile); got != tc.want {
				t.Errorf("slugFor = %q, want %q", got, tc.want)
			}
		})
	}
}
