apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: amberdark-wildcard
  namespace: traefik
spec:
  secretName: amberdark-wildcard-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - amberdark.net
    - "*.amberdark.net"
  duration: 2160h
  renewBefore: 720h
