apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kube-ops-view
  namespace: infra-control
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Kube Ops View"
    gethomepage.dev/description: "Cluster Visualizer"
    gethomepage.dev/group: "Home & Tools"
    gethomepage.dev/weight: "12"
    gethomepage.dev/icon: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/kubernetes.png"
    gethomepage.dev/href: "http://kube-ops-view.talos00"
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`kube-ops-view.talos00`)
      kind: Rule
      services:
        - name: kube-ops-view
          port: 80
