---
apiVersion: v1
kind: Service
metadata:
  name: fchat-bouncer
  labels:
    app.kubernetes.io/name: fchat-bouncer
    app.kubernetes.io/part-of: catalyst
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fchat-bouncer
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
