---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: posterizarr
  labels:
    app: posterizarr
    app.kubernetes.io/name: posterizarr
    app.kubernetes.io/part-of: arr-stack
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Posterizarr"
    gethomepage.dev/description: "Poster Overlay Generator"
    gethomepage.dev/group: "Media Management"
    gethomepage.dev/icon: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/plex.png"
    gethomepage.dev/href: "http://posterizarr.talos00"
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`posterizarr.talos00`)
      kind: Rule
      services:
        - name: posterizarr
          port: 8000
