#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  Talos Cluster Provisioning — PLANNER                                        ║
# ║  Preflight + generate configs + print the exact rebuild command sequence.     ║
# ║  APPLIES NOTHING.                                                            ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# WHY THIS SCRIPT NO LONGER APPLIES ANYTHING (TALOS-ow7w)
#
# It used to. It read ${PROJECT_ROOT}/configs/controlplane.yaml, applied it insecurely,
# bootstrapped etcd, and removed the control-plane taint. Three separate things broke that:
#
#   1. configs/controlplane.yaml IS GONE. Machine configs are generated by talhelper from
#      configs/talconfig.yaml now. The old hand-maintained tree is archived at
#      .scratch/__configs/ and is NOT the source of truth.
#
#   2. THE CLUSTER IS NO LONGER SINGLE-NODE. This script provisioned one node. The cluster
#      is five: three control planes (talos00/01/03) and two GPU workers (talos02-gpu/
#      talos06), each with its own install disk, factory schematic and patch set. "Apply one
#      config and bootstrap" is not a rebuild of this cluster; it is a rebuild of a different,
#      simpler cluster that no longer exists.
#
#   3. STEP 8.5 WAS ACTIVELY WRONG. It ran `kubectl taint nodes ... control-plane:NoSchedule-`.
#      talos00 carries a DELIBERATE hard NoSchedule taint declared in machine.nodeTaints (see
#      configs/patches/talos00-controlplane-taint.yaml). Talos applies nodeTaints through a
#      code path that ignores allowSchedulingOnControlPlanes, so that kubectl would either
#      no-op or fight the declared config until Talos put the taint back. It encoded an
#      assumption — "the control-plane taint is unwanted" — that the cluster has since reversed.
#
# A faithful automated port would have to sequence a five-node from-scratch build: bring each
# node up in maintenance mode, apply five different configs, bootstrap exactly one control
# plane, wait for etcd quorum to form across three, and only then join the workers. None of
# that can be exercised without wiping the cluster, so writing it blind would produce a
# destructive script whose failure modes are unknown — and a destructive script that
# half-works is far worse than one that refuses to start.
#
# So this is a PLANNER. Everything it does is read-only or local: it checks preconditions,
# regenerates the configs, and prints the exact commands a rebuild needs, in order, for an
# operator to run deliberately. talhelper emits those commands itself (`talhelper gencommand`),
# so the plan cannot drift from talconfig.yaml the way a hardcoded sequence would.
#
# For an EXISTING cluster you almost certainly want one of these instead:
#     task talos:verify           regenerate and diff against every live node
#     task talos:verify-dry-run   ask each node what applying would actually do

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"

# ══════════════════════════════════════════════════════════════════════════════
# Configuration
# ══════════════════════════════════════════════════════════════════════════════
CONFIG_DIR="${PROJECT_ROOT}/configs"
TALCONFIG="${CONFIG_DIR}/talconfig.yaml"
TALSECRET="${CONFIG_DIR}/talsecret.yaml"

print_banner "
██████╗ ██████╗  ██████╗ ██╗   ██╗██╗███████╗██╗ ██████╗ ███╗   ██╗
██╔══██╗██╔══██╗██╔═══██╗██║   ██║██║██╔════╝██║██╔═══██╗████╗  ██║
██████╔╝██████╔╝██║   ██║██║   ██║██║███████╗██║██║   ██║██╔██╗ ██║
██╔═══╝ ██╔══██╗██║   ██║╚██╗ ██╔╝██║╚════██║██║██║   ██║██║╚██╗██║
██║     ██║  ██║╚██████╔╝ ╚████╔╝ ██║███████║██║╚██████╔╝██║ ╚████║
╚═╝     ╚═╝  ╚═╝ ╚═════╝   ╚═══╝  ╚═╝╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝
                   ${ICON_LIGHTNING} Rebuild Planner — applies nothing ${ICON_LIGHTNING}
" "$MAGENTA"

# ══════════════════════════════════════════════════════════════════════════════
# Step 1: Preflight — the toolchain and the declarative source
# ══════════════════════════════════════════════════════════════════════════════
log_step "1" "Preflight"

if ! command -v talhelper > /dev/null 2>&1; then
  error "talhelper is not installed — it is now how machine configs are produced"
  log_note "brew install talhelper"
  exit 1
fi
success "talhelper $(talhelper --version 2>&1 | awk '{print $NF}')"

if [[ ! -f "$TALCONFIG" ]]; then
  error "Missing $TALCONFIG"
  log_note "This is the declarative source for every machine config. Without it there is"
  log_note "nothing to generate from. It is tracked in git — check your working tree."
  exit 1
fi
success "talconfig.yaml present"

# talsecret.yaml holds the cluster CA and bootstrap tokens. Regenerating it produces a
# DIFFERENT cluster: new CA, every existing kubeconfig and talosconfig invalid, etcd
# unjoinable by any surviving node. It is gitignored, so a fresh clone will not have it.
if [[ ! -f "$TALSECRET" ]]; then
  error "Missing $TALSECRET"
  log_note "This file holds the cluster CA and bootstrap tokens, and it is gitignored."
  log_note "It is backed up in 1Password — see docs/05-runbooks/talsecret-1password-backup.md."
  log_note ""
  log_note "Do NOT 'fix' this with 'talhelper gensecret'. That mints a NEW certificate"
  log_note "authority, which makes this a different cluster: every existing kubeconfig and"
  log_note "talosconfig stops working and no surviving node can rejoin etcd. Restore the"
  log_note "backup instead. Generate fresh secrets only if you are truly starting over."
  exit 1
fi
success "talsecret.yaml present"
echo ""

# ══════════════════════════════════════════════════════════════════════════════
# Step 2: Refuse to plan a rebuild over a cluster that is alive
# ══════════════════════════════════════════════════════════════════════════════
log_step "2" "Checking whether these nodes are already a live cluster"

# The original script targeted one bare VM in maintenance mode, so "is something already
# running here?" was not a question worth asking. With five nodes carrying live workloads it
# is the most important one in the file.
# `|| true`: grep exits 1 on no match, and common.sh sets `set -e`. A talconfig with no
# ipAddress must reach the explicit check below with a clear message, not die on a bare grep.
NODE_IPS=()
while IFS= read -r _ip; do
  if [[ -n "$_ip" ]]; then
    NODE_IPS+=("$_ip")
  fi
done < <(grep -E '^[[:space:]]+ipAddress:' "$TALCONFIG" 2> /dev/null | awk '{print $2}' || true)

if [[ ${#NODE_IPS[@]} -eq 0 ]]; then
  error "Could not read any ipAddress from $TALCONFIG"
  log_note "Refusing to continue: without the node list this script cannot tell whether it"
  log_note "would be planning against a live cluster."
  exit 1
fi

LIVE_NODES=()
for ip in "${NODE_IPS[@]}"; do
  if talosctl --talosconfig "$TALOSCONFIG" --nodes "$ip" version --client=false > /dev/null 2>&1; then
    LIVE_NODES+=("$ip")
  fi
done

if [[ ${#LIVE_NODES[@]} -gt 0 ]]; then
  warn "${#LIVE_NODES[@]}/${#NODE_IPS[@]} node(s) are already running Talos and answering the API:"
  for ip in "${LIVE_NODES[@]}"; do
    echo -e "    ${DIM}${ip}${RESET}"
  done
  echo ""
  error "This is a from-scratch rebuild planner. That cluster is alive."
  log_note "You are almost certainly looking for one of these instead:"
  log_note "  task talos:verify           regenerate and diff against every live node"
  log_note "  task talos:verify-dry-run   ask each node what applying would actually do"
  log_note ""
  log_note "If you genuinely intend to plan a rebuild of a live cluster, re-run with:"
  log_note "  REBUILD_LIVE_CLUSTER=yes ./scripts/provision.sh"
  log_note "(Even then this script still applies nothing — it only prints the plan.)"
  if [[ "${REBUILD_LIVE_CLUSTER:-no}" != "yes" ]]; then
    exit 1
  fi
  warn "REBUILD_LIVE_CLUSTER=yes — continuing to print the plan anyway"
else
  success "No node is answering the Talos API — consistent with a from-scratch build"
fi
echo ""

# ══════════════════════════════════════════════════════════════════════════════
# Step 3: Generate the machine configs (local only — writes configs/clusterconfig/)
# ══════════════════════════════════════════════════════════════════════════════
log_step "3" "Generating machine configs from talconfig.yaml"

if ! (cd "$CONFIG_DIR" && talhelper genconfig); then
  error "talhelper genconfig failed — fix talconfig.yaml before planning a rebuild"
  exit 1
fi
success "Wrote configs/clusterconfig/ (gitignored — these files carry certs and tokens)"
echo ""

# ══════════════════════════════════════════════════════════════════════════════
# Step 4: Print the plan
# ══════════════════════════════════════════════════════════════════════════════
log_step "4" "Rebuild plan"

# Emitted by talhelper from talconfig.yaml rather than hardcoded here, so adding or removing
# a node in talconfig.yaml updates this plan automatically instead of silently skipping it.
print_section "RUN THESE FROM ${CONFIG_DIR}"
echo ""
echo -e "${DIM}The generated commands use ./clusterconfig/... relative paths, so cd there first:${RESET}"
echo -e "    ${BOLD}cd ${CONFIG_DIR}${RESET}"
echo ""

print_subsection "1. Apply configs — every node must be in maintenance mode (freshly booted, no config)"
(cd "$CONFIG_DIR" && talhelper gencommand apply --extra-flags=--insecure)
echo ""
echo -e "${DIM}Each node reboots and installs to its declared disk. Wait for all of them to come${RESET}"
echo -e "${DIM}back before continuing — roughly 90s each, in parallel.${RESET}"
echo ""

print_subsection "2. Bootstrap etcd — EXACTLY ONE control plane, ONCE"
(cd "$CONFIG_DIR" && talhelper gencommand bootstrap)
echo ""
echo -e "${DIM}Running this a second time, or on a second control plane, splits etcd into two${RESET}"
echo -e "${DIM}clusters that will never agree. The other control planes join on their own.${RESET}"
echo ""

print_subsection "3. Fetch kubeconfig"
(cd "$CONFIG_DIR" && talhelper gencommand kubeconfig)
echo ""

print_subsection "4. Health"
(cd "$CONFIG_DIR" && talhelper gencommand health)
echo ""

print_summary "success" \
  "Nothing was applied. Everything above is for you to run deliberately."

print_next_steps \
  "Read the plan above before running any of it" \
  "task talos:verify-dry-run  ${DIM}# what applying would do, per node, read-only${RESET}" \
  "task k8s:kubeconfig-merge  ${DIM}# once the cluster answers${RESET}" \
  "Flux reconciles all infrastructure from git once the API is up"

# Control-plane taints are DECLARED (configs/patches/talos00-controlplane-taint.yaml,
# memory-constrained-taint.yaml). Do not remove them with kubectl — see the header.
