---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metube
  labels:
    app: metube
    app.kubernetes.io/name: metube
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: metube
  template:
    metadata:
      labels:
        app: metube
        app.kubernetes.io/name: metube
    spec:
      containers:
        - name: metube
          image: ghcr.io/alexta69/metube:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Los_Angeles
          volumeMounts:
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: metube-downloads
