---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: metube
  labels:
    app: metube
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`metube.talos00`)
      kind: Rule
      services:
        - name: metube
          port: 8081
