// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent.proto

package ec2agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_NODE_TYPE_UNSPECIFIED NodeType = 0
	NodeType_NODE_TYPE_LIGHTHOUSE  NodeType = 1 // k3s server + liqo + nebula lighthouse
	NodeType_NODE_TYPE_GPU_WORKER  NodeType = 2 // k3s agent + ollama + GPU
	NodeType_NODE_TYPE_CPU_WORKER  NodeType = 3 // k3s agent, no GPU
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_UNSPECIFIED",
		1: "NODE_TYPE_LIGHTHOUSE",
		2: "NODE_TYPE_GPU_WORKER",
		3: "NODE_TYPE_CPU_WORKER",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_UNSPECIFIED": 0,
		"NODE_TYPE_LIGHTHOUSE":  1,
		"NODE_TYPE_GPU_WORKER":  2,
		"NODE_TYPE_CPU_WORKER":  3,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type ServiceState int32

const (
	ServiceState_SERVICE_STATE_UNSPECIFIED   ServiceState = 0
	ServiceState_SERVICE_STATE_RUNNING       ServiceState = 1
	ServiceState_SERVICE_STATE_STOPPED       ServiceState = 2
	ServiceState_SERVICE_STATE_STARTING      ServiceState = 3
	ServiceState_SERVICE_STATE_ERROR         ServiceState = 4
	ServiceState_SERVICE_STATE_NOT_INSTALLED ServiceState = 5
)

// Enum value maps for ServiceState.
var (
	ServiceState_name = map[int32]string{
		0: "SERVICE_STATE_UNSPECIFIED",
		1: "SERVICE_STATE_RUNNING",
		2: "SERVICE_STATE_STOPPED",
		3: "SERVICE_STATE_STARTING",
		4: "SERVICE_STATE_ERROR",
		5: "SERVICE_STATE_NOT_INSTALLED",
	}
	ServiceState_value = map[string]int32{
		"SERVICE_STATE_UNSPECIFIED":   0,
		"SERVICE_STATE_RUNNING":       1,
		"SERVICE_STATE_STOPPED":       2,
		"SERVICE_STATE_STARTING":      3,
		"SERVICE_STATE_ERROR":         4,
		"SERVICE_STATE_NOT_INSTALLED": 5,
	}
)

func (x ServiceState) Enum() *ServiceState {
	p := new(ServiceState)
	*p = x
	return p
}

func (x ServiceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (ServiceState) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x ServiceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceState.Descriptor instead.
func (ServiceState) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

type HealthState int32

const (
	HealthState_HEALTH_STATE_UNSPECIFIED HealthState = 0
	HealthState_HEALTH_STATE_HEALTHY     HealthState = 1
	HealthState_HEALTH_STATE_DEGRADED    HealthState = 2 // Partially working
	HealthState_HEALTH_STATE_UNHEALTHY   HealthState = 3
)

// Enum value maps for HealthState.
var (
	HealthState_name = map[int32]string{
		0: "HEALTH_STATE_UNSPECIFIED",
		1: "HEALTH_STATE_HEALTHY",
		2: "HEALTH_STATE_DEGRADED",
		3: "HEALTH_STATE_UNHEALTHY",
	}
	HealthState_value = map[string]int32{
		"HEALTH_STATE_UNSPECIFIED": 0,
		"HEALTH_STATE_HEALTHY":     1,
		"HEALTH_STATE_DEGRADED":    2,
		"HEALTH_STATE_UNHEALTHY":   3,
	}
)

func (x HealthState) Enum() *HealthState {
	p := new(HealthState)
	*p = x
	return p
}

func (x HealthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[2].Descriptor()
}

func (HealthState) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[2]
}

func (x HealthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthState.Descriptor instead.
func (HealthState) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED     CommandType = 0
	CommandType_COMMAND_TYPE_SHUTDOWN        CommandType = 1 // Graceful shutdown
	CommandType_COMMAND_TYPE_REBOOT          CommandType = 2
	CommandType_COMMAND_TYPE_DRAIN           CommandType = 3 // Drain k3s workloads then shutdown
	CommandType_COMMAND_TYPE_PULL_MODEL      CommandType = 4 // Pull ollama model (args: model=name)
	CommandType_COMMAND_TYPE_UNLOAD_MODEL    CommandType = 5 // Unload model from VRAM
	CommandType_COMMAND_TYPE_EXEC            CommandType = 6 // Execute arbitrary command (args: cmd=...)
	CommandType_COMMAND_TYPE_UPDATE_CONFIG   CommandType = 7 // Update agent config
	CommandType_COMMAND_TYPE_RESTART_SERVICE CommandType = 8 // Restart a service (args: service=name)
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_SHUTDOWN",
		2: "COMMAND_TYPE_REBOOT",
		3: "COMMAND_TYPE_DRAIN",
		4: "COMMAND_TYPE_PULL_MODEL",
		5: "COMMAND_TYPE_UNLOAD_MODEL",
		6: "COMMAND_TYPE_EXEC",
		7: "COMMAND_TYPE_UPDATE_CONFIG",
		8: "COMMAND_TYPE_RESTART_SERVICE",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":     0,
		"COMMAND_TYPE_SHUTDOWN":        1,
		"COMMAND_TYPE_REBOOT":          2,
		"COMMAND_TYPE_DRAIN":           3,
		"COMMAND_TYPE_PULL_MODEL":      4,
		"COMMAND_TYPE_UNLOAD_MODEL":    5,
		"COMMAND_TYPE_EXEC":            6,
		"COMMAND_TYPE_UPDATE_CONFIG":   7,
		"COMMAND_TYPE_RESTART_SERVICE": 8,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[3].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[3]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[4].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[4]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

type RegisterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                                             // Unique node identifier (instance-id or hostname)
	NodeType         NodeType               `protobuf:"varint,2,opt,name=node_type,json=nodeType,proto3,enum=ec2agent.v1.NodeType" json:"node_type,omitempty"`                            // lighthouse, gpu-worker, cpu-worker
	InstanceId       string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`                                                 // AWS instance ID (if applicable)
	NebulaIp         string                 `protobuf:"bytes,4,opt,name=nebula_ip,json=nebulaIp,proto3" json:"nebula_ip,omitempty"`                                                       // Nebula mesh IP (e.g., 10.42.2.1)
	PublicIp         string                 `protobuf:"bytes,5,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`                                                       // Public IP (if any)
	Region           string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`                                                                           // AWS region or "homelab"
	AvailabilityZone string                 `protobuf:"bytes,7,opt,name=availability_zone,json=availabilityZone,proto3" json:"availability_zone,omitempty"`                               // AZ or empty
	Labels           map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional labels/tags
	Capabilities     *NodeCapabilities      `protobuf:"bytes,9,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *RegisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterRequest) GetNebulaIp() string {
	if x != nil {
		return x.NebulaIp
	}
	return ""
}

func (x *RegisterRequest) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *RegisterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterRequest) GetAvailabilityZone() string {
	if x != nil {
		return x.AvailabilityZone
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetCapabilities() *NodeCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Accepted             bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AssignedId           string                 `protobuf:"bytes,3,opt,name=assigned_id,json=assignedId,proto3" json:"assigned_id,omitempty"`                                  // Control plane may assign a different ID
	HeartbeatIntervalSec int32                  `protobuf:"varint,4,opt,name=heartbeat_interval_sec,json=heartbeatIntervalSec,proto3" json:"heartbeat_interval_sec,omitempty"` // How often to send heartbeats
	StatusIntervalSec    int32                  `protobuf:"varint,5,opt,name=status_interval_sec,json=statusIntervalSec,proto3" json:"status_interval_sec,omitempty"`          // How often to send full status
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAssignedId() string {
	if x != nil {
		return x.AssignedId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSec() int32 {
	if x != nil {
		return x.HeartbeatIntervalSec
	}
	return 0
}

func (x *RegisterResponse) GetStatusIntervalSec() int32 {
	if x != nil {
		return x.StatusIntervalSec
	}
	return 0
}

type NodeCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasGpu        bool                   `protobuf:"varint,1,opt,name=has_gpu,json=hasGpu,proto3" json:"has_gpu,omitempty"`
	GpuModel      string                 `protobuf:"bytes,2,opt,name=gpu_model,json=gpuModel,proto3" json:"gpu_model,omitempty"` // e.g., "NVIDIA T4", "NVIDIA A10G"
	GpuCount      int32                  `protobuf:"varint,3,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	GpuMemoryMb   int64                  `protobuf:"varint,4,opt,name=gpu_memory_mb,json=gpuMemoryMb,proto3" json:"gpu_memory_mb,omitempty"`
	CpuCores      int32                  `protobuf:"varint,5,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb      int64                  `protobuf:"varint,6,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskMb        int64                  `protobuf:"varint,7,opt,name=disk_mb,json=diskMb,proto3" json:"disk_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCapabilities) Reset() {
	*x = NodeCapabilities{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapabilities) ProtoMessage() {}

func (x *NodeCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapabilities.ProtoReflect.Descriptor instead.
func (*NodeCapabilities) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *NodeCapabilities) GetHasGpu() bool {
	if x != nil {
		return x.HasGpu
	}
	return false
}

func (x *NodeCapabilities) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

func (x *NodeCapabilities) GetGpuCount() int32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *NodeCapabilities) GetGpuMemoryMb() int64 {
	if x != nil {
		return x.GpuMemoryMb
	}
	return 0
}

func (x *NodeCapabilities) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *NodeCapabilities) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *NodeCapabilities) GetDiskMb() int64 {
	if x != nil {
		return x.DiskMb
	}
	return 0
}

// AgentMessage is sent from worker agent to control plane
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Status
	//	*AgentMessage_CommandResult
	//	*AgentMessage_Log
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetStatus() *NodeStatus {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

func (x *AgentMessage) GetLog() *LogEntry {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Log); ok {
			return x.Log
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Status struct {
	Status *NodeStatus `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type AgentMessage_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,2,opt,name=command_result,json=commandResult,proto3,oneof"`
}

type AgentMessage_Log struct {
	Log *LogEntry `protobuf:"bytes,3,opt,name=log,proto3,oneof"`
}

func (*AgentMessage_Status) isAgentMessage_Payload() {}

func (*AgentMessage_CommandResult) isAgentMessage_Payload() {}

func (*AgentMessage_Log) isAgentMessage_Payload() {}

// ControlMessage is sent from control plane to worker agent
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_Command
	//	*ControlMessage_Ack
	//	*ControlMessage_Config
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ControlMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ControlMessage) GetConfig() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Config); ok {
			return x.Config
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_Command struct {
	Command *Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type ControlMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type ControlMessage_Config struct {
	Config *ConfigUpdate `protobuf:"bytes,3,opt,name=config,proto3,oneof"`
}

func (*ControlMessage_Command) isControlMessage_Payload() {}

func (*ControlMessage_Ack) isControlMessage_Payload() {}

func (*ControlMessage_Config) isControlMessage_Payload() {}

type NodeStatus struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	NodeId    string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Service health
	Nebula *ServiceStatus `protobuf:"bytes,3,opt,name=nebula,proto3" json:"nebula,omitempty"`
	K3S    *ServiceStatus `protobuf:"bytes,4,opt,name=k3s,proto3" json:"k3s,omitempty"`
	Ollama *ServiceStatus `protobuf:"bytes,5,opt,name=ollama,proto3" json:"ollama,omitempty"`
	Liqo   *ServiceStatus `protobuf:"bytes,6,opt,name=liqo,proto3" json:"liqo,omitempty"`
	// Resource usage
	Resources *ResourceUsage `protobuf:"bytes,7,opt,name=resources,proto3" json:"resources,omitempty"`
	// GPU status (if applicable)
	Gpus []*GPUStatus `protobuf:"bytes,8,rep,name=gpus,proto3" json:"gpus,omitempty"`
	// Ollama models (if applicable)
	LoadedModels []*OllamaModel `protobuf:"bytes,9,rep,name=loaded_models,json=loadedModels,proto3" json:"loaded_models,omitempty"`
	// Uptime and idle tracking
	UptimeSeconds int64 `protobuf:"varint,10,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	IdleSeconds   int64 `protobuf:"varint,11,opt,name=idle_seconds,json=idleSeconds,proto3" json:"idle_seconds,omitempty"` // Seconds since last ollama request
	// Overall health
	Health        HealthState `protobuf:"varint,12,opt,name=health,proto3,enum=ec2agent.v1.HealthState" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *NodeStatus) GetNebula() *ServiceStatus {
	if x != nil {
		return x.Nebula
	}
	return nil
}

func (x *NodeStatus) GetK3S() *ServiceStatus {
	if x != nil {
		return x.K3S
	}
	return nil
}

func (x *NodeStatus) GetOllama() *ServiceStatus {
	if x != nil {
		return x.Ollama
	}
	return nil
}

func (x *NodeStatus) GetLiqo() *ServiceStatus {
	if x != nil {
		return x.Liqo
	}
	return nil
}

func (x *NodeStatus) GetResources() *ResourceUsage {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *NodeStatus) GetGpus() []*GPUStatus {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *NodeStatus) GetLoadedModels() []*OllamaModel {
	if x != nil {
		return x.LoadedModels
	}
	return nil
}

func (x *NodeStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *NodeStatus) GetIdleSeconds() int64 {
	if x != nil {
		return x.IdleSeconds
	}
	return 0
}

func (x *NodeStatus) GetHealth() HealthState {
	if x != nil {
		return x.Health
	}
	return HealthState_HEALTH_STATE_UNSPECIFIED
}

type ServiceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         ServiceState           `protobuf:"varint,1,opt,name=state,proto3,enum=ec2agent.v1.ServiceState" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message if not healthy
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceStatus) GetState() ServiceState {
	if x != nil {
		return x.State
	}
	return ServiceState_SERVICE_STATE_UNSPECIFIED
}

func (x *ServiceStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServiceStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ResourceUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsedMb  int64                  `protobuf:"varint,2,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	MemoryTotalMb int64                  `protobuf:"varint,3,opt,name=memory_total_mb,json=memoryTotalMb,proto3" json:"memory_total_mb,omitempty"`
	DiskUsedMb    int64                  `protobuf:"varint,4,opt,name=disk_used_mb,json=diskUsedMb,proto3" json:"disk_used_mb,omitempty"`
	DiskTotalMb   int64                  `protobuf:"varint,5,opt,name=disk_total_mb,json=diskTotalMb,proto3" json:"disk_total_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceUsage) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceUsage) GetMemoryUsedMb() int64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *ResourceUsage) GetMemoryTotalMb() int64 {
	if x != nil {
		return x.MemoryTotalMb
	}
	return 0
}

func (x *ResourceUsage) GetDiskUsedMb() int64 {
	if x != nil {
		return x.DiskUsedMb
	}
	return 0
}

func (x *ResourceUsage) GetDiskTotalMb() int64 {
	if x != nil {
		return x.DiskTotalMb
	}
	return 0
}

type GPUStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Index              int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // e.g., "NVIDIA T4"
	MemoryUsedMb       int64                  `protobuf:"varint,3,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	MemoryTotalMb      int64                  `protobuf:"varint,4,opt,name=memory_total_mb,json=memoryTotalMb,proto3" json:"memory_total_mb,omitempty"`
	UtilizationPercent float64                `protobuf:"fixed64,5,opt,name=utilization_percent,json=utilizationPercent,proto3" json:"utilization_percent,omitempty"`
	TemperatureC       int32                  `protobuf:"varint,6,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GPUStatus) Reset() {
	*x = GPUStatus{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUStatus) ProtoMessage() {}

func (x *GPUStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUStatus.ProtoReflect.Descriptor instead.
func (*GPUStatus) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GPUStatus) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPUStatus) GetMemoryUsedMb() int64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *GPUStatus) GetMemoryTotalMb() int64 {
	if x != nil {
		return x.MemoryTotalMb
	}
	return 0
}

func (x *GPUStatus) GetUtilizationPercent() float64 {
	if x != nil {
		return x.UtilizationPercent
	}
	return 0
}

func (x *GPUStatus) GetTemperatureC() int32 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

type OllamaModel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // e.g., "llama3.2:latest"
	SizeBytes       int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CurrentlyLoaded bool                   `protobuf:"varint,3,opt,name=currently_loaded,json=currentlyLoaded,proto3" json:"currently_loaded,omitempty"` // In VRAM
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OllamaModel) Reset() {
	*x = OllamaModel{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OllamaModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OllamaModel) ProtoMessage() {}

func (x *OllamaModel) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OllamaModel.ProtoReflect.Descriptor instead.
func (*OllamaModel) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *OllamaModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OllamaModel) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *OllamaModel) GetCurrentlyLoaded() bool {
	if x != nil {
		return x.CurrentlyLoaded
	}
	return false
}

type Command struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommandId      string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // Unique ID for tracking
	Type           CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=ec2agent.v1.CommandType" json:"type,omitempty"`
	Args           map[string]string      `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Command-specific arguments
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                                // 0 = no timeout
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *Command) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"` // Error message if failed
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Received      bool                   `protobuf:"varint,2,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *Ack) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Ack) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

type ConfigUpdate struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatIntervalSec int32                  `protobuf:"varint,1,opt,name=heartbeat_interval_sec,json=heartbeatIntervalSec,proto3" json:"heartbeat_interval_sec,omitempty"`
	StatusIntervalSec    int32                  `protobuf:"varint,2,opt,name=status_interval_sec,json=statusIntervalSec,proto3" json:"status_interval_sec,omitempty"`
	IdleShutdownMinutes  int32                  `protobuf:"varint,3,opt,name=idle_shutdown_minutes,json=idleShutdownMinutes,proto3" json:"idle_shutdown_minutes,omitempty"` // 0 = disabled
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ConfigUpdate) GetHeartbeatIntervalSec() int32 {
	if x != nil {
		return x.HeartbeatIntervalSec
	}
	return 0
}

func (x *ConfigUpdate) GetStatusIntervalSec() int32 {
	if x != nil {
		return x.StatusIntervalSec
	}
	return 0
}

func (x *ConfigUpdate) GetIdleShutdownMinutes() int32 {
	if x != nil {
		return x.IdleShutdownMinutes
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=ec2agent.v1.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // e.g., "ollama", "k3s", "nebula"
	Fields        map[string]string      `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type FleetStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filters
	NodeType      NodeType    `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=ec2agent.v1.NodeType" json:"node_type,omitempty"` // Filter by type
	Health        HealthState `protobuf:"varint,2,opt,name=health,proto3,enum=ec2agent.v1.HealthState" json:"health,omitempty"`                  // Filter by health
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetStatusRequest) Reset() {
	*x = FleetStatusRequest{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetStatusRequest) ProtoMessage() {}

func (x *FleetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetStatusRequest.ProtoReflect.Descriptor instead.
func (*FleetStatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *FleetStatusRequest) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *FleetStatusRequest) GetHealth() HealthState {
	if x != nil {
		return x.Health
	}
	return HealthState_HEALTH_STATE_UNSPECIFIED
}

type FleetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeSummary         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Summary       *FleetSummary          `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetStatusResponse) Reset() {
	*x = FleetStatusResponse{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetStatusResponse) ProtoMessage() {}

func (x *FleetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetStatusResponse.ProtoReflect.Descriptor instead.
func (*FleetStatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *FleetStatusResponse) GetNodes() []*NodeSummary {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *FleetStatusResponse) GetSummary() *FleetSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type NodeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType      NodeType               `protobuf:"varint,2,opt,name=node_type,json=nodeType,proto3,enum=ec2agent.v1.NodeType" json:"node_type,omitempty"`
	Health        HealthState            `protobuf:"varint,3,opt,name=health,proto3,enum=ec2agent.v1.HealthState" json:"health,omitempty"`
	NebulaIp      string                 `protobuf:"bytes,4,opt,name=nebula_ip,json=nebulaIp,proto3" json:"nebula_ip,omitempty"`
	InstanceId    string                 `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Connected     bool                   `protobuf:"varint,6,opt,name=connected,proto3" json:"connected,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	IdleSeconds   int64                  `protobuf:"varint,9,opt,name=idle_seconds,json=idleSeconds,proto3" json:"idle_seconds,omitempty"`
	// Quick stats
	CpuPercent    float64 `protobuf:"fixed64,10,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64 `protobuf:"fixed64,11,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	GpuCount      int32   `protobuf:"varint,12,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	LoadedModels  int32   `protobuf:"varint,13,opt,name=loaded_models,json=loadedModels,proto3" json:"loaded_models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSummary) Reset() {
	*x = NodeSummary{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSummary) ProtoMessage() {}

func (x *NodeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSummary.ProtoReflect.Descriptor instead.
func (*NodeSummary) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *NodeSummary) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeSummary) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *NodeSummary) GetHealth() HealthState {
	if x != nil {
		return x.Health
	}
	return HealthState_HEALTH_STATE_UNSPECIFIED
}

func (x *NodeSummary) GetNebulaIp() string {
	if x != nil {
		return x.NebulaIp
	}
	return ""
}

func (x *NodeSummary) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *NodeSummary) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *NodeSummary) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *NodeSummary) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *NodeSummary) GetIdleSeconds() int64 {
	if x != nil {
		return x.IdleSeconds
	}
	return 0
}

func (x *NodeSummary) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeSummary) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *NodeSummary) GetGpuCount() int32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *NodeSummary) GetLoadedModels() int32 {
	if x != nil {
		return x.LoadedModels
	}
	return 0
}

type FleetSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalNodes     int32                  `protobuf:"varint,1,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	HealthyNodes   int32                  `protobuf:"varint,2,opt,name=healthy_nodes,json=healthyNodes,proto3" json:"healthy_nodes,omitempty"`
	UnhealthyNodes int32                  `protobuf:"varint,3,opt,name=unhealthy_nodes,json=unhealthyNodes,proto3" json:"unhealthy_nodes,omitempty"`
	GpuNodes       int32                  `protobuf:"varint,4,opt,name=gpu_nodes,json=gpuNodes,proto3" json:"gpu_nodes,omitempty"`
	TotalGpus      int32                  `protobuf:"varint,5,opt,name=total_gpus,json=totalGpus,proto3" json:"total_gpus,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FleetSummary) Reset() {
	*x = FleetSummary{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetSummary) ProtoMessage() {}

func (x *FleetSummary) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetSummary.ProtoReflect.Descriptor instead.
func (*FleetSummary) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *FleetSummary) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *FleetSummary) GetHealthyNodes() int32 {
	if x != nil {
		return x.HealthyNodes
	}
	return 0
}

func (x *FleetSummary) GetUnhealthyNodes() int32 {
	if x != nil {
		return x.UnhealthyNodes
	}
	return 0
}

func (x *FleetSummary) GetGpuNodes() int32 {
	if x != nil {
		return x.GpuNodes
	}
	return 0
}

func (x *FleetSummary) GetTotalGpus() int32 {
	if x != nil {
		return x.TotalGpus
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\vec2agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x03\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x122\n" +
	"\tnode_type\x18\x02 \x01(\x0e2\x15.ec2agent.v1.NodeTypeR\bnodeType\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x1b\n" +
	"\tnebula_ip\x18\x04 \x01(\tR\bnebulaIp\x12\x1b\n" +
	"\tpublic_ip\x18\x05 \x01(\tR\bpublicIp\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12+\n" +
	"\x11availability_zone\x18\a \x01(\tR\x10availabilityZone\x12@\n" +
	"\x06labels\x18\b \x03(\v2(.ec2agent.v1.RegisterRequest.LabelsEntryR\x06labels\x12A\n" +
	"\fcapabilities\x18\t \x01(\v2\x1d.ec2agent.v1.NodeCapabilitiesR\fcapabilities\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x01\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vassigned_id\x18\x03 \x01(\tR\n" +
	"assignedId\x124\n" +
	"\x16heartbeat_interval_sec\x18\x04 \x01(\x05R\x14heartbeatIntervalSec\x12.\n" +
	"\x13status_interval_sec\x18\x05 \x01(\x05R\x11statusIntervalSec\"\xdc\x01\n" +
	"\x10NodeCapabilities\x12\x17\n" +
	"\ahas_gpu\x18\x01 \x01(\bR\x06hasGpu\x12\x1b\n" +
	"\tgpu_model\x18\x02 \x01(\tR\bgpuModel\x12\x1b\n" +
	"\tgpu_count\x18\x03 \x01(\x05R\bgpuCount\x12\"\n" +
	"\rgpu_memory_mb\x18\x04 \x01(\x03R\vgpuMemoryMb\x12\x1b\n" +
	"\tcpu_cores\x18\x05 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x06 \x01(\x03R\bmemoryMb\x12\x17\n" +
	"\adisk_mb\x18\a \x01(\x03R\x06diskMb\"\xbc\x01\n" +
	"\fAgentMessage\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x17.ec2agent.v1.NodeStatusH\x00R\x06status\x12C\n" +
	"\x0ecommand_result\x18\x02 \x01(\v2\x1a.ec2agent.v1.CommandResultH\x00R\rcommandResult\x12)\n" +
	"\x03log\x18\x03 \x01(\v2\x15.ec2agent.v1.LogEntryH\x00R\x03logB\t\n" +
	"\apayload\"\xa8\x01\n" +
	"\x0eControlMessage\x120\n" +
	"\acommand\x18\x01 \x01(\v2\x14.ec2agent.v1.CommandH\x00R\acommand\x12$\n" +
	"\x03ack\x18\x02 \x01(\v2\x10.ec2agent.v1.AckH\x00R\x03ack\x123\n" +
	"\x06config\x18\x03 \x01(\v2\x19.ec2agent.v1.ConfigUpdateH\x00R\x06configB\t\n" +
	"\apayload\"\xc6\x04\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x122\n" +
	"\x06nebula\x18\x03 \x01(\v2\x1a.ec2agent.v1.ServiceStatusR\x06nebula\x12,\n" +
	"\x03k3s\x18\x04 \x01(\v2\x1a.ec2agent.v1.ServiceStatusR\x03k3s\x122\n" +
	"\x06ollama\x18\x05 \x01(\v2\x1a.ec2agent.v1.ServiceStatusR\x06ollama\x12.\n" +
	"\x04liqo\x18\x06 \x01(\v2\x1a.ec2agent.v1.ServiceStatusR\x04liqo\x128\n" +
	"\tresources\x18\a \x01(\v2\x1a.ec2agent.v1.ResourceUsageR\tresources\x12*\n" +
	"\x04gpus\x18\b \x03(\v2\x16.ec2agent.v1.GPUStatusR\x04gpus\x12=\n" +
	"\rloaded_models\x18\t \x03(\v2\x18.ec2agent.v1.OllamaModelR\floadedModels\x12%\n" +
	"\x0euptime_seconds\x18\n" +
	" \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\fidle_seconds\x18\v \x01(\x03R\vidleSeconds\x120\n" +
	"\x06health\x18\f \x01(\x0e2\x18.ec2agent.v1.HealthStateR\x06health\"\x81\x01\n" +
	"\rServiceStatus\x12/\n" +
	"\x05state\x18\x01 \x01(\x0e2\x19.ec2agent.v1.ServiceStateR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"\xc4\x01\n" +
	"\rResourceUsage\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12$\n" +
	"\x0ememory_used_mb\x18\x02 \x01(\x03R\fmemoryUsedMb\x12&\n" +
	"\x0fmemory_total_mb\x18\x03 \x01(\x03R\rmemoryTotalMb\x12 \n" +
	"\fdisk_used_mb\x18\x04 \x01(\x03R\n" +
	"diskUsedMb\x12\"\n" +
	"\rdisk_total_mb\x18\x05 \x01(\x03R\vdiskTotalMb\"\xd9\x01\n" +
	"\tGPUStatus\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x0ememory_used_mb\x18\x03 \x01(\x03R\fmemoryUsedMb\x12&\n" +
	"\x0fmemory_total_mb\x18\x04 \x01(\x03R\rmemoryTotalMb\x12/\n" +
	"\x13utilization_percent\x18\x05 \x01(\x01R\x12utilizationPercent\x12#\n" +
	"\rtemperature_c\x18\x06 \x01(\x05R\ftemperatureC\"k\n" +
	"\vOllamaModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12)\n" +
	"\x10currently_loaded\x18\x03 \x01(\bR\x0fcurrentlyLoaded\"\xec\x01\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.ec2agent.v1.CommandTypeR\x04type\x122\n" +
	"\x04args\x18\x03 \x03(\v2\x1e.ec2agent.v1.Command.ArgsEntryR\x04args\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x01\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\"@\n" +
	"\x03Ack\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1a\n" +
	"\breceived\x18\x02 \x01(\bR\breceived\"\xa8\x01\n" +
	"\fConfigUpdate\x124\n" +
	"\x16heartbeat_interval_sec\x18\x01 \x01(\x05R\x14heartbeatIntervalSec\x12.\n" +
	"\x13status_interval_sec\x18\x02 \x01(\x05R\x11statusIntervalSec\x122\n" +
	"\x15idle_shutdown_minutes\x18\x03 \x01(\x05R\x13idleShutdownMinutes\"\x99\x02\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12+\n" +
	"\x05level\x18\x02 \x01(\x0e2\x15.ec2agent.v1.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x129\n" +
	"\x06fields\x18\x05 \x03(\v2!.ec2agent.v1.LogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"`\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"z\n" +
	"\x12FleetStatusRequest\x122\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x15.ec2agent.v1.NodeTypeR\bnodeType\x120\n" +
	"\x06health\x18\x02 \x01(\x0e2\x18.ec2agent.v1.HealthStateR\x06health\"z\n" +
	"\x13FleetStatusResponse\x12.\n" +
	"\x05nodes\x18\x01 \x03(\v2\x18.ec2agent.v1.NodeSummaryR\x05nodes\x123\n" +
	"\asummary\x18\x02 \x01(\v2\x19.ec2agent.v1.FleetSummaryR\asummary\"\xf5\x03\n" +
	"\vNodeSummary\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x122\n" +
	"\tnode_type\x18\x02 \x01(\x0e2\x15.ec2agent.v1.NodeTypeR\bnodeType\x120\n" +
	"\x06health\x18\x03 \x01(\x0e2\x18.ec2agent.v1.HealthStateR\x06health\x12\x1b\n" +
	"\tnebula_ip\x18\x04 \x01(\tR\bnebulaIp\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\tR\n" +
	"instanceId\x12\x1c\n" +
	"\tconnected\x18\x06 \x01(\bR\tconnected\x127\n" +
	"\tlast_seen\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12%\n" +
	"\x0euptime_seconds\x18\b \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\fidle_seconds\x18\t \x01(\x03R\vidleSeconds\x12\x1f\n" +
	"\vcpu_percent\x18\n" +
	" \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\v \x01(\x01R\rmemoryPercent\x12\x1b\n" +
	"\tgpu_count\x18\f \x01(\x05R\bgpuCount\x12#\n" +
	"\rloaded_models\x18\r \x01(\x05R\floadedModels\"\xb9\x01\n" +
	"\fFleetSummary\x12\x1f\n" +
	"\vtotal_nodes\x18\x01 \x01(\x05R\n" +
	"totalNodes\x12#\n" +
	"\rhealthy_nodes\x18\x02 \x01(\x05R\fhealthyNodes\x12'\n" +
	"\x0funhealthy_nodes\x18\x03 \x01(\x05R\x0eunhealthyNodes\x12\x1b\n" +
	"\tgpu_nodes\x18\x04 \x01(\x05R\bgpuNodes\x12\x1d\n" +
	"\n" +
	"total_gpus\x18\x05 \x01(\x05R\ttotalGpus*s\n" +
	"\bNodeType\x12\x19\n" +
	"\x15NODE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14NODE_TYPE_LIGHTHOUSE\x10\x01\x12\x18\n" +
	"\x14NODE_TYPE_GPU_WORKER\x10\x02\x12\x18\n" +
	"\x14NODE_TYPE_CPU_WORKER\x10\x03*\xb9\x01\n" +
	"\fServiceState\x12\x1d\n" +
	"\x19SERVICE_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SERVICE_STATE_RUNNING\x10\x01\x12\x19\n" +
	"\x15SERVICE_STATE_STOPPED\x10\x02\x12\x1a\n" +
	"\x16SERVICE_STATE_STARTING\x10\x03\x12\x17\n" +
	"\x13SERVICE_STATE_ERROR\x10\x04\x12\x1f\n" +
	"\x1bSERVICE_STATE_NOT_INSTALLED\x10\x05*|\n" +
	"\vHealthState\x12\x1c\n" +
	"\x18HEALTH_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14HEALTH_STATE_HEALTHY\x10\x01\x12\x19\n" +
	"\x15HEALTH_STATE_DEGRADED\x10\x02\x12\x1a\n" +
	"\x16HEALTH_STATE_UNHEALTHY\x10\x03*\x8c\x02\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15COMMAND_TYPE_SHUTDOWN\x10\x01\x12\x17\n" +
	"\x13COMMAND_TYPE_REBOOT\x10\x02\x12\x16\n" +
	"\x12COMMAND_TYPE_DRAIN\x10\x03\x12\x1b\n" +
	"\x17COMMAND_TYPE_PULL_MODEL\x10\x04\x12\x1d\n" +
	"\x19COMMAND_TYPE_UNLOAD_MODEL\x10\x05\x12\x15\n" +
	"\x11COMMAND_TYPE_EXEC\x10\x06\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_UPDATE_CONFIG\x10\a\x12 \n" +
	"\x1cCOMMAND_TYPE_RESTART_SERVICE\x10\b*w\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x042\xbf\x02\n" +
	"\fAgentControl\x12E\n" +
	"\aConnect\x12\x19.ec2agent.v1.AgentMessage\x1a\x1b.ec2agent.v1.ControlMessage(\x010\x01\x12G\n" +
	"\bRegister\x12\x1c.ec2agent.v1.RegisterRequest\x1a\x1d.ec2agent.v1.RegisterResponse\x12J\n" +
	"\tHeartbeat\x12\x1d.ec2agent.v1.HeartbeatRequest\x1a\x1e.ec2agent.v1.HeartbeatResponse\x12S\n" +
	"\x0eGetFleetStatus\x12\x1f.ec2agent.v1.FleetStatusRequest\x1a .ec2agent.v1.FleetStatusResponseB\xa2\x01\n" +
	"\x0fcom.ec2agent.v1B\n" +
	"AgentProtoP\x01Z6github.com/thebranchdriftcatalyst/ec2-agent;ec2agentv1\xa2\x02\x03EXX\xaa\x02\vEc2agent.V1\xca\x02\vEc2agent\\V1\xe2\x02\x17Ec2agent\\V1\\GPBMetadata\xea\x02\fEc2agent::V1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_agent_proto_goTypes = []any{
	(NodeType)(0),                 // 0: ec2agent.v1.NodeType
	(ServiceState)(0),             // 1: ec2agent.v1.ServiceState
	(HealthState)(0),              // 2: ec2agent.v1.HealthState
	(CommandType)(0),              // 3: ec2agent.v1.CommandType
	(LogLevel)(0),                 // 4: ec2agent.v1.LogLevel
	(*RegisterRequest)(nil),       // 5: ec2agent.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 6: ec2agent.v1.RegisterResponse
	(*NodeCapabilities)(nil),      // 7: ec2agent.v1.NodeCapabilities
	(*AgentMessage)(nil),          // 8: ec2agent.v1.AgentMessage
	(*ControlMessage)(nil),        // 9: ec2agent.v1.ControlMessage
	(*NodeStatus)(nil),            // 10: ec2agent.v1.NodeStatus
	(*ServiceStatus)(nil),         // 11: ec2agent.v1.ServiceStatus
	(*ResourceUsage)(nil),         // 12: ec2agent.v1.ResourceUsage
	(*GPUStatus)(nil),             // 13: ec2agent.v1.GPUStatus
	(*OllamaModel)(nil),           // 14: ec2agent.v1.OllamaModel
	(*Command)(nil),               // 15: ec2agent.v1.Command
	(*CommandResult)(nil),         // 16: ec2agent.v1.CommandResult
	(*Ack)(nil),                   // 17: ec2agent.v1.Ack
	(*ConfigUpdate)(nil),          // 18: ec2agent.v1.ConfigUpdate
	(*LogEntry)(nil),              // 19: ec2agent.v1.LogEntry
	(*HeartbeatRequest)(nil),      // 20: ec2agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 21: ec2agent.v1.HeartbeatResponse
	(*FleetStatusRequest)(nil),    // 22: ec2agent.v1.FleetStatusRequest
	(*FleetStatusResponse)(nil),   // 23: ec2agent.v1.FleetStatusResponse
	(*NodeSummary)(nil),           // 24: ec2agent.v1.NodeSummary
	(*FleetSummary)(nil),          // 25: ec2agent.v1.FleetSummary
	nil,                           // 26: ec2agent.v1.RegisterRequest.LabelsEntry
	nil,                           // 27: ec2agent.v1.Command.ArgsEntry
	nil,                           // 28: ec2agent.v1.LogEntry.FieldsEntry
	(*timestamppb.Timestamp)(nil), // 29: google.protobuf.Timestamp
}
var file_agent_proto_depIdxs = []int32{
	0,  // 0: ec2agent.v1.RegisterRequest.node_type:type_name -> ec2agent.v1.NodeType
	26, // 1: ec2agent.v1.RegisterRequest.labels:type_name -> ec2agent.v1.RegisterRequest.LabelsEntry
	7,  // 2: ec2agent.v1.RegisterRequest.capabilities:type_name -> ec2agent.v1.NodeCapabilities
	10, // 3: ec2agent.v1.AgentMessage.status:type_name -> ec2agent.v1.NodeStatus
	16, // 4: ec2agent.v1.AgentMessage.command_result:type_name -> ec2agent.v1.CommandResult
	19, // 5: ec2agent.v1.AgentMessage.log:type_name -> ec2agent.v1.LogEntry
	15, // 6: ec2agent.v1.ControlMessage.command:type_name -> ec2agent.v1.Command
	17, // 7: ec2agent.v1.ControlMessage.ack:type_name -> ec2agent.v1.Ack
	18, // 8: ec2agent.v1.ControlMessage.config:type_name -> ec2agent.v1.ConfigUpdate
	29, // 9: ec2agent.v1.NodeStatus.timestamp:type_name -> google.protobuf.Timestamp
	11, // 10: ec2agent.v1.NodeStatus.nebula:type_name -> ec2agent.v1.ServiceStatus
	11, // 11: ec2agent.v1.NodeStatus.k3s:type_name -> ec2agent.v1.ServiceStatus
	11, // 12: ec2agent.v1.NodeStatus.ollama:type_name -> ec2agent.v1.ServiceStatus
	11, // 13: ec2agent.v1.NodeStatus.liqo:type_name -> ec2agent.v1.ServiceStatus
	12, // 14: ec2agent.v1.NodeStatus.resources:type_name -> ec2agent.v1.ResourceUsage
	13, // 15: ec2agent.v1.NodeStatus.gpus:type_name -> ec2agent.v1.GPUStatus
	14, // 16: ec2agent.v1.NodeStatus.loaded_models:type_name -> ec2agent.v1.OllamaModel
	2,  // 17: ec2agent.v1.NodeStatus.health:type_name -> ec2agent.v1.HealthState
	1,  // 18: ec2agent.v1.ServiceStatus.state:type_name -> ec2agent.v1.ServiceState
	3,  // 19: ec2agent.v1.Command.type:type_name -> ec2agent.v1.CommandType
	27, // 20: ec2agent.v1.Command.args:type_name -> ec2agent.v1.Command.ArgsEntry
	29, // 21: ec2agent.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 22: ec2agent.v1.LogEntry.level:type_name -> ec2agent.v1.LogLevel
	28, // 23: ec2agent.v1.LogEntry.fields:type_name -> ec2agent.v1.LogEntry.FieldsEntry
	29, // 24: ec2agent.v1.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	29, // 25: ec2agent.v1.HeartbeatResponse.server_time:type_name -> google.protobuf.Timestamp
	0,  // 26: ec2agent.v1.FleetStatusRequest.node_type:type_name -> ec2agent.v1.NodeType
	2,  // 27: ec2agent.v1.FleetStatusRequest.health:type_name -> ec2agent.v1.HealthState
	24, // 28: ec2agent.v1.FleetStatusResponse.nodes:type_name -> ec2agent.v1.NodeSummary
	25, // 29: ec2agent.v1.FleetStatusResponse.summary:type_name -> ec2agent.v1.FleetSummary
	0,  // 30: ec2agent.v1.NodeSummary.node_type:type_name -> ec2agent.v1.NodeType
	2,  // 31: ec2agent.v1.NodeSummary.health:type_name -> ec2agent.v1.HealthState
	29, // 32: ec2agent.v1.NodeSummary.last_seen:type_name -> google.protobuf.Timestamp
	8,  // 33: ec2agent.v1.AgentControl.Connect:input_type -> ec2agent.v1.AgentMessage
	5,  // 34: ec2agent.v1.AgentControl.Register:input_type -> ec2agent.v1.RegisterRequest
	20, // 35: ec2agent.v1.AgentControl.Heartbeat:input_type -> ec2agent.v1.HeartbeatRequest
	22, // 36: ec2agent.v1.AgentControl.GetFleetStatus:input_type -> ec2agent.v1.FleetStatusRequest
	9,  // 37: ec2agent.v1.AgentControl.Connect:output_type -> ec2agent.v1.ControlMessage
	6,  // 38: ec2agent.v1.AgentControl.Register:output_type -> ec2agent.v1.RegisterResponse
	21, // 39: ec2agent.v1.AgentControl.Heartbeat:output_type -> ec2agent.v1.HeartbeatResponse
	23, // 40: ec2agent.v1.AgentControl.GetFleetStatus:output_type -> ec2agent.v1.FleetStatusResponse
	37, // [37:41] is the sub-list for method output_type
	33, // [33:37] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentMessage_Status)(nil),
		(*AgentMessage_CommandResult)(nil),
		(*AgentMessage_Log)(nil),
	}
	file_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*ControlMessage_Command)(nil),
		(*ControlMessage_Ack)(nil),
		(*ControlMessage_Config)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
